/* SPDX-License-Identifier: GPL-3.0-only */
/*
 * GENERATED by tools/make-lucide-glyphs.py - do not edit.
 *
 * One alpha cell per Lucide icon per size notes draws at,
 * rasterized from the SVGs in assets/icons/notes.  Lucide is
 * stroke-only on a 24-unit grid with round caps and joins, so a pixel
 * is inside an icon exactly when its distance to the nearest path is
 * at most half the stroke width - which is what the generator
 * measures, at sixty-four samples per pixel.
 *
 * Each size is rasterized natively rather than resampled from a
 * larger one, and its stroke is widened or narrowed to a whole
 * number of pixels and snapped to the grid that stroke lands on.
 * That is what an icon font's hinting does, and at sixteen pixels it
 * is the whole of the difference between a crisp mark and a smear.
 *
 * Lucide is ISC licensed; see assets/icons/lucide/LICENSE.
 */
#ifndef PHIPIA_NOTES_GLYPHS_H
#define PHIPIA_NOTES_GLYPHS_H

#include <stddef.h>
#include <stdint.h>

#define NOTES_LUCIDE_SIZES 2U

static const uint32_t notes_lucide_size[NOTES_LUCIDE_SIZES] = {
    16U, 20U
};

/* list.svg */
static const uint8_t notes_lucide_list_16[16 * 16] = {
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0, 207,   0,   0, 231, 255, 255, 255, 255, 255, 255, 255, 255, 231,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0, 207,   0,   0, 231, 255, 255, 255, 255, 255, 255, 255, 255, 231,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0, 207,   0,   0, 231, 255, 255, 255, 255, 255, 255, 255, 255, 231,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
};
static const uint8_t notes_lucide_list_20[20 * 20] = {
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,
      0,   0, 207, 207,   0,   0, 207, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 207,   0,
      0,   0, 207, 207,   0,   0, 207, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 207,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,
      0,   0, 207, 207,   0,   0, 207, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 207,   0,
      0,   0, 207, 207,   0,   0, 207, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 207,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,
      0,   0, 207, 207,   0,   0, 207, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 207,   0,
      0,   0, 207, 207,   0,   0, 207, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 207,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,
};

struct notes_lucide_entry {
    const char *name;
    const uint8_t *alpha[NOTES_LUCIDE_SIZES];
};

static const struct notes_lucide_entry notes_lucide[] = {
    { "list", { notes_lucide_list_16, notes_lucide_list_20 } },
};

#define NOTES_LUCIDE_COUNT (sizeof(notes_lucide) / sizeof(notes_lucide[0]))

#endif
