/* SPDX-License-Identifier: GPL-3.0-only */
/*
 * GENERATED by tools/make-notes-marks.py - do not edit.
 *
 * The four typographic marks on the notes formatting bar at 20px,
 * each set in the cut that means it:
 *
 *     bold           'B' from Inter-Bold.ttf
 *     italic         'I' from Inter-Italic.ttf
 *     underline      'U' from Inter-Regular.ttf
 *     strikethrough  'S' from Inter-Regular.ttf
 *
 * Cropped to its own ink and carrying that ink's size, so the caller
 * centres what is drawn rather than a cell full of unused descender
 * space.  `baseline` is where the baseline falls inside the ink, which
 * is what an underline is placed against.
 *
 * Inter is under the SIL Open Font License 1.1; see
 * assets/fonts/Inter-LICENSE.txt.
 */
#ifndef PHIPIA_NOTES_MARKS_H
#define PHIPIA_NOTES_MARKS_H

#include <stddef.h>
#include <stdint.h>

#define NOTES_MARK_SIZE 20U

/* 'B' from Inter-Bold.ttf */
static const uint8_t notes_mark_bold[12 * 14] = {
     176, 255, 255, 255, 255, 255, 249, 224, 158,  36,   0,   0,
     176, 255, 255, 255, 255, 255, 255, 255, 255, 241,  46,   0,
     176, 255, 255, 132,  80,  81, 111, 225, 255, 255, 178,   0,
     176, 255, 255,  76,   0,   0,   0,  63, 255, 255, 219,   0,
     176, 255, 255,  76,   0,   0,   0,  72, 255, 255, 181,   0,
     176, 255, 255, 132,  80,  81, 119, 234, 255, 236,  47,   0,
     176, 255, 255, 255, 255, 255, 255, 255, 194,  36,   0,   0,
     176, 255, 255, 255, 255, 255, 255, 255, 255, 238,  76,   0,
     176, 255, 255,  76,   0,   0,  19, 118, 255, 255, 245,  25,
     176, 255, 255,  76,   0,   0,   0,   0, 183, 255, 255, 100,
     176, 255, 255,  76,   0,   0,   0,   0, 194, 255, 255, 105,
     176, 255, 255, 132,  80,  80,  96, 171, 255, 255, 254,  43,
     176, 255, 255, 255, 255, 255, 255, 255, 255, 255, 137,   0,
     176, 255, 255, 255, 255, 255, 253, 234, 184,  81,   0,   0,
};

/* 'I' from Inter-Italic.ttf */
static const uint8_t notes_mark_italic[6 * 14] = {
       0,   0,   0, 211, 254,  11,
       0,   0,   4, 249, 221,   0,
       0,   0,  43, 255, 177,   0,
       0,   0,  87, 255, 132,   0,
       0,   0, 132, 255,  88,   0,
       0,   0, 176, 255,  44,   0,
       0,   0, 220, 250,   5,   0,
       0,  10, 253, 211,   0,   0,
       0,  53, 255, 167,   0,   0,
       0,  97, 255, 123,   0,   0,
       0, 141, 255,  78,   0,   0,
       0, 186, 255,  34,   0,   0,
       0, 230, 244,   1,   0,   0,
      18, 255, 202,   0,   0,   0,
};

/* 'U' from Inter-Regular.ttf */
static const uint8_t notes_mark_underline[13 * 14] = {
      60, 255, 156,   0,   0,   0,   0,   0,   0,   0, 188, 255,  32,
      60, 255, 156,   0,   0,   0,   0,   0,   0,   0, 188, 255,  32,
      60, 255, 156,   0,   0,   0,   0,   0,   0,   0, 188, 255,  32,
      60, 255, 156,   0,   0,   0,   0,   0,   0,   0, 188, 255,  32,
      60, 255, 156,   0,   0,   0,   0,   0,   0,   0, 188, 255,  32,
      60, 255, 156,   0,   0,   0,   0,   0,   0,   0, 188, 255,  32,
      60, 255, 156,   0,   0,   0,   0,   0,   0,   0, 188, 255,  32,
      60, 255, 156,   0,   0,   0,   0,   0,   0,   0, 188, 255,  32,
      60, 255, 156,   0,   0,   0,   0,   0,   0,   0, 188, 255,  32,
      46, 255, 172,   0,   0,   0,   0,   0,   0,   0, 204, 255,  17,
      10, 244, 237,  12,   0,   0,   0,   0,   0,  28, 251, 227,   0,
       0, 140, 255, 181,  16,   0,   0,   0,  24, 198, 255, 112,   0,
       0,   5, 178, 255, 242, 175, 154, 180, 246, 255, 155,   1,   0,
       0,   0,   0,  87, 184, 232, 249, 230, 175,  73,   0,   0,   0,
};

/* 'S' from Inter-Regular.ttf */
static const uint8_t notes_mark_strikethrough[11 * 14] = {
       0,   0,  60, 170, 230, 249, 233, 177,  70,   0,   0,
       0, 119, 255, 248, 180, 156, 181, 248, 255, 135,   0,
      40, 253, 218,  27,   0,   0,   0,  28, 215, 255,  53,
     102, 255, 108,   0,   0,   0,   0,   0,  70, 164,  72,
      81, 255, 144,   0,   0,   0,   0,   0,   0,   0,   0,
       9, 213, 255, 170,  58,   2,   0,   0,   0,   0,   0,
       0,  23, 167, 252, 255, 237, 172,  96,  10,   0,   0,
       0,   0,   0,  23, 104, 173, 241, 255, 232,  80,   0,
       0,   0,   0,   0,   0,   0,   7,  82, 223, 250,  62,
       0,   0,   0,   0,   0,   0,   0,   0,  60, 255, 159,
     164, 208,  28,   0,   0,   0,   0,   0,  54, 255, 163,
     129, 255, 178,  19,   0,   0,   0,  21, 199, 255,  92,
      10, 197, 255, 238, 182, 154, 179, 244, 255, 167,   2,
       0,   5, 109, 198, 241, 251, 233, 183,  86,   0,   0,
};

struct notes_mark {
    const char *name;
    const uint8_t *alpha;
    uint16_t width;
    uint16_t height;
    uint16_t baseline;   /* rows from the top of the ink */
};

static const struct notes_mark notes_marks[] = {
    { "bold", notes_mark_bold, 12U, 14U, 14U },
    { "italic", notes_mark_italic, 6U, 14U, 14U },
    { "underline", notes_mark_underline, 13U, 14U, 14U },
    { "strikethrough", notes_mark_strikethrough, 11U, 14U, 14U },
};

#define NOTES_MARK_COUNT (sizeof(notes_marks) / sizeof(notes_marks[0]))

#endif
