// SPDX-License-Identifier: GPL-3.0-only
//! The render graph.
//!
//! A render is a pure function of a project and an instant (R-4.1), and this
//! is the shape that makes it one: a graph of tasks with typed inputs, no
//! ambient state, and no way to observe when anything ran.
//!
//! Two invariants are structural rather than checked. A node may only refer to
//! nodes added before it, so **a cycle is unrepresentable** — there is no
//! `add_edge` to get wrong and no validation pass to forget. And every node's
//! identity is a digest over its kind, its parameters and its inputs'
//! identities, so two nodes that would compute the same picture *are* the same
//! node as far as the cache is concerned (R-8.5).
//!
//! Phipia is single-core, so this evaluates serially today. It is written as
//! though it did not: nothing here depends on evaluation order, and the tests
//! prove that by evaluating the same graph in every order a scheduler could
//! choose and comparing the results (R-6.2). The day cores arrive, nothing in
//! this model changes.

use alloc::vec::Vec;

use media_editor_core::{Digest, Fixed, Rational, Sha256};
use media_editor_media::{
    AlphaState, CacheKey, ColourDescription, Frame, FrameDescription, FramePool, TestPattern,
};

use crate::composite;
use crate::convert;
use crate::status::{RenderStatus, Result};

/// How many nodes one graph may hold.
///
/// A policy bound. A render graph for a frame of a timeline is tens of nodes;
/// one that reaches this has been generated by a loop that meant to stop.
pub const MAX_NODES: usize = 4096;

/// A reference to a node in a graph.
///
/// It is an index, and it is only ever handed out by [`Graph::add`] for a node
/// that already exists, which is what makes forward references — and therefore
/// cycles — impossible to write.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct NodeId(usize);

impl NodeId {
    /// Where in the graph this node sits.
    #[must_use]
    pub const fn index(self) -> usize {
        self.0
    }

    /// Build an identifier from an index, for tests that need to name a node
    /// that does not exist.
    ///
    /// Deliberately awkward to reach for: every identifier a caller should
    /// have comes from [`Graph::add`], and one built here is exactly the thing
    /// the graph is supposed to refuse.
    #[must_use]
    pub const fn from_index_for_test(index: usize) -> Self {
        Self(index)
    }
}

/// One step of a render.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Node {
    /// A frame drawn from nothing, which is what a generator is.
    Pattern {
        /// What to draw.
        pattern: TestPattern,
        /// What the result is.
        description: FrameDescription,
    },
    /// A frame of a single value.
    Blank {
        /// What the result is.
        description: FrameDescription,
    },
    /// A frame of nothing at all: no light, and no coverage either.
    ///
    /// The other kind of nothing, and the two are not interchangeable.
    /// [`Node::Blank`] is an opaque black slug, which is what a *programme*
    /// shows where it has nothing — a viewer displays black leader and an
    /// export writes black frames. This is what *material* looks like where it
    /// has nothing, and a nested sequence composited onto black would blank
    /// out every track beneath it wherever it happened to be empty.
    Empty {
        /// What the result is. Must carry coverage: a format without it cannot
        /// express absence at all.
        description: FrameDescription,
    },
    /// A frame of media, named by what that media *is*.
    ///
    /// By content digest rather than by any project's identifier for it,
    /// because that is what makes a cached frame usable: the same footage in
    /// two projects is the same footage, and a node that named it by a
    /// project-local index would cache it twice and could never tell that the
    /// file had been swapped underneath.
    ///
    /// Where the frame comes from is a [`Media`], because a graph knows how to
    /// combine frames and nothing about where they live.
    Source {
        /// Which media.
        media: Digest,
        /// Which tick of it.
        tick: i64,
        /// What the result is.
        description: FrameDescription,
    },
    /// A frame at a fraction of its opacity.
    ///
    /// Every channel, coverage included: in premultiplied form the colour has
    /// already been multiplied by the coverage, so halving one means halving
    /// the other. Anything else leaves a frame claiming more colour than its
    /// coverage allows, which [`crate::over`] refuses and is right to.
    Fade {
        /// What to fade.
        input: NodeId,
        /// How much of it is showing.
        opacity: Rational,
    },
    /// A frame moved: scaled, shifted, or turned.
    ///
    /// The linear part is dimensionless and the offset is in fractions of the
    /// frame, so the node is the same node at every size — which is what lets
    /// a proxy render and a finish render share a cache key for everything
    /// above it. The map acts about the frame's **centre**, because scaling
    /// about the corner sends a picture sliding off to the lower right the
    /// moment somebody drags a scale slider.
    Transform {
        /// What to move.
        input: NodeId,
        /// The linear part, row-major and dimensionless.
        linear: [Rational; 4],
        /// The move, in fractions of the frame.
        offset: (Rational, Rational),
        /// The point the linear part acts about, in fractions of the frame.
        ///
        /// A field here rather than folded into `offset` by the caller,
        /// because the two are only interchangeable in *pixels*: the vector
        /// from the centre to the anchor scales per axis, and a linear part
        /// that mixes the axes — which is to say any rotation — does not
        /// commute with that scaling. See [`crate::resample::Mapping::about`].
        anchor: (Rational, Rational),
        /// Whether to weigh by area or between four samples.
        bilinear: bool,
    },
    /// A frame with everything outside a shape taken away.
    ///
    /// The corners are fractions of the frame, so the node is the same node at
    /// every size — which is what lets a proxy render and a finish render
    /// share a cache key for everything above the mask.
    Mask {
        /// What to mask.
        input: NodeId,
        /// The shape, in fractions of the frame.
        corners: alloc::vec::Vec<(Rational, Rational)>,
        /// Whether what is kept is what lies outside it.
        inverted: bool,
    },
    /// A picture made of words, at a size and a place somebody chose.
    ///
    /// A **source**, not a filter: a title is media the program generates, so
    /// this sits where a [`Node::Source`] would and everything above it — the
    /// grade, the mask, the transform, the fade — is the same machinery a
    /// recording goes through. That is the whole reason a title is media
    /// rather than a kind of item.
    ///
    /// Transparent everywhere the letters are not. The ink is three fractions
    /// of **full light** rather than three code values, for the reason the
    /// model gives: a code value is a number in an encoding, and the same
    /// number is a different colour in sRGB than in a linear working space.
    /// Naming it in light means the conversion happens once, here, through the
    /// table this frame's own description spells its colours with — so a
    /// limited-range title writes 235 for white and not the illegal 255 a
    /// hard-coded byte would.
    ///
    /// Distinct from [`Node::Legend`], which carries the words and *nothing
    /// else* because a slate's caption is not something anybody chose the look
    /// of. Here somebody did.
    Type {
        /// What to draw it as.
        description: FrameDescription,
        /// What it says, a line at a time.
        lines: alloc::vec::Vec<alloc::string::String>,
        /// The em, as a fraction of the frame's height.
        size: Rational,
        /// Where the middle of the block sits across the frame.
        across: Rational,
        /// And down it.
        down: Rational,
        /// How the lines sit against one another.
        alignment: crate::font::Alignment,
        /// What colour the letters are, as fractions of full light.
        ink: [Rational; 3],
    },
    /// A frame with a line of type set across it.
    ///
    /// A caption on a slate, not a title tool. It carries the words and
    /// nothing else — no size, no place, no colour — because everything a
    /// caption's *look* could be is a decision that would have to be the same
    /// on every slate to be worth anything, and a parameter nobody varies is a
    /// parameter that goes wrong in one place and nowhere else. Titles as
    /// something a project contains are a different feature with a different
    /// node.
    ///
    /// The words are in the identity, so two slates saying different things
    /// are two cache entries, and the same slate twice is one.
    ///
    /// It draws **nothing** on a frame too small to read it. That is not a
    /// failure and not a refusal: a slate whose caption is a grey smear has
    /// told the viewer something false about how much it knows, and the
    /// stripes underneath already say the one thing that matters.
    Legend {
        /// What to write on.
        input: NodeId,
        /// What it says.
        text: alloc::string::String,
        /// What it says instead when there is no room to read the first.
        ///
        /// Two strings rather than one, because a caption on a proxy has a
        /// real choice to make and neither answer is right at both sizes.
        /// "MEDIA OFFLINE 4F3C9A21" needs a frame three hundred pixels across
        /// to be read; the eight characters that *identify* the clip need a
        /// hundred and sixty. Setting the long one small enough to fit is a
        /// grey smear, and dropping straight to nothing throws away the part
        /// somebody actually needs.
        ///
        /// So: the whole sentence, then the part that matters, then nothing.
        brief: alloc::string::String,
    },
    /// A frame revealed behind a wipe's edge.
    ///
    /// [`Node::Fade`] with a different opacity at every pixel, which is what a
    /// wipe is. The edge's *position* is carried rather than the coverage
    /// plane it produces: four rationals hash into a node's identity and a
    /// plane of a million bytes would too, at a million times the cost, for a
    /// value that is a pure function of them and the frame's own size.
    Wipe {
        /// What to reveal.
        input: NodeId,
        /// How much of the direction runs across the picture.
        across: Rational,
        /// How much of it runs down.
        down: Rational,
        /// How far along its travel the edge is.
        fraction: Rational,
        /// How much of that travel the edge fades over.
        softness: Rational,
    },
    /// A frame with its coverage associated the other way.
    ///
    /// Premultiplying or dividing back out, named as its own step because
    /// [`Node::Convert`] refuses to do it: gaining, losing and re-associating
    /// alpha are three operations with three names, and a colour conversion
    /// that quietly performed one is the reason a keyed title arrives opaque.
    ///
    /// It exists because a look and a composite want opposite things. `over`
    /// is only correct on premultiplied samples; a lookup table is a
    /// non-linear function and on premultiplied samples computes `f(ac)` where
    /// `a·f(c)` was wanted. So a graded layer is fetched straight, graded, and
    /// associated here — which loses nothing, because the frame was never
    /// premultiplied to begin with.
    Associate {
        /// What to re-associate.
        input: NodeId,
        /// What the result is, which differs from the input only in how its
        /// coverage is carried.
        target: FrameDescription,
    },
    /// A frame with a look applied, some of the way on.
    ///
    /// The look is named by its digest rather than carried, because a cube is
    /// 35,937 triples and a graph is rebuilt for every instant. That also
    /// makes the node's identity depend on what the look *is*: a grade edited
    /// between two renders is a different key rather than a stale hit.
    ///
    /// The strength is a field rather than a second node in front of this one
    /// because it is not a second picture: it says where along the table's own
    /// output this frame lands, which is a thing only the table can compute.
    /// It is in the identity for the reason everything else here is — a look
    /// coming on over a shot is a different picture every frame, and a key
    /// that ignored the strength would serve the whole arrival out of one
    /// cache entry.
    Look {
        /// What to grade.
        input: NodeId,
        /// Which look.
        look: Digest,
        /// How far from ungraded to graded, from none of it to all of it.
        strength: Rational,
    },
    /// One frame over another.
    ///
    /// The two are stored in one array rather than as two named fields so that
    /// [`Node::inputs`] can hand back a slice of *both*. A version that
    /// returned only one of them would let a cycle through the other slip past
    /// the check that makes cycles unrepresentable — the whole point of that
    /// check being that it needs nobody to remember it.
    Over {
        /// What is underneath, then what goes on top.
        layers: [NodeId; 2],
    },
    /// A frame in another description.
    Convert {
        /// Where the picture comes from.
        input: NodeId,
        /// What the result is.
        target: FrameDescription,
    },
}

impl Node {
    /// What this node produces, without producing it — where it can say.
    ///
    /// A fade and an `over` produce whatever their inputs are described as, so
    /// they cannot answer on their own. [`Graph::description`] can, because it
    /// can follow the edge.
    #[must_use]
    pub const fn description(&self) -> Option<FrameDescription> {
        match self {
            Self::Pattern { description, .. }
            | Self::Blank { description }
            | Self::Empty { description }
            | Self::Type { description, .. }
            | Self::Source { description, .. } => Some(*description),
            Self::Convert { target, .. } | Self::Associate { target, .. } => Some(*target),
            Self::Fade { .. }
            | Self::Wipe { .. }
            | Self::Transform { .. }
            | Self::Mask { .. }
            | Self::Over { .. }
            | Self::Legend { .. }
            | Self::Look { .. } => None,
        }
    }

    /// The nodes this one reads.
    #[must_use]
    pub fn inputs(&self) -> &[NodeId] {
        match self {
            Self::Pattern { .. }
            | Self::Blank { .. }
            | Self::Empty { .. }
            | Self::Source { .. }
            | Self::Type { .. } => &[],
            Self::Convert { input, .. }
            | Self::Fade { input, .. }
            | Self::Wipe { input, .. }
            | Self::Mask { input, .. }
            | Self::Legend { input, .. }
            | Self::Transform { input, .. }
            | Self::Look { input, .. }
            | Self::Associate { input, .. } => core::slice::from_ref(input),
            Self::Over { layers } => layers.as_slice(),
        }
    }
}

/// Where the things a graph names by digest come from.
///
/// A graph knows how to combine frames and nothing about where anything lives.
/// Decoding, reading, waiting and caching a file's own structure all sit behind
/// this, and none of it is the graph's business.
///
/// Two methods, because there are two kinds of heavy thing a graph refers to
/// without holding: frames of media, and lookup tables. Both are named by
/// content digest rather than by a handle, so the same footage or the same
/// grade in two projects is one cached thing, and a file swapped underneath is
/// a different key rather than a stale hit.
pub trait Library {
    /// The frame at `tick` of the media with this content digest.
    ///
    /// # Errors
    ///
    /// Whatever the source cannot do.
    fn frame(&mut self, media: Digest, tick: i64, description: FrameDescription) -> Result<Frame>;

    /// Whether this media can be read at all.
    ///
    /// Asked *before* a graph is built rather than discovered while evaluating
    /// one, and that is the whole reason it exists as a separate question.
    ///
    /// A source node's identity is a digest over the media, the tick and the
    /// description — and **not** over whether the bytes happened to be
    /// reachable. So a node that quietly fell back to a slate when a file was
    /// missing would put that slate in the cache under the key of the real
    /// picture, and hand it back after the drive was plugged in again. That is
    /// exactly the staleness a content-addressed cache exists to prevent, and
    /// it is why the decision belongs to whatever plans the graph.
    ///
    /// The default is `true`: a library that cannot tell is a library that
    /// should try, and failing at `frame` is a worse answer than refusing to
    /// plan.
    fn available(&mut self, media: Digest) -> bool {
        let _ = media;
        true
    }

    /// The look with this digest.
    ///
    /// A cube is 35,937 triples and a graph is rebuilt for every instant, so a
    /// node names a look by what it *is* and fetches it from here — the same
    /// bargain as media, for the same reasons. A default is deliberately not
    /// provided: an implementor that renders graded material and forgot to
    /// write this should fail to compile rather than refuse at run time.
    ///
    /// # Errors
    ///
    /// Whatever the library cannot do.
    fn look(&mut self, look: Digest) -> Result<crate::look::Look>;

    /// One row of a frame of media, as a frame one row high.
    ///
    /// What a library needs to serve [`Graph::row`]. The default **refuses**
    /// rather than fetching the whole frame and slicing it, and that is the
    /// decision worth arguing for: a default that quietly loaded eight
    /// megabytes to hand back six thousand bytes would make a row-at-a-time
    /// renderer look like it was working while doing exactly the thing it
    /// exists to avoid. A library that can serve rows says so by writing this;
    /// one that cannot says so by not.
    ///
    /// The frame handed back is `width × 1` in the same format and colour as
    /// the description asked for.
    ///
    /// # Errors
    ///
    /// [`RenderStatus::NoRowForm`] by default, or whatever the library cannot
    /// do.
    fn row(
        &mut self,
        media: Digest,
        tick: i64,
        description: FrameDescription,
        row: usize,
    ) -> Result<Frame> {
        let _ = (media, tick, description, row);
        Err(RenderStatus::NoRowForm)
    }
}

/// A graph of render steps.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Graph {
    nodes: Vec<Node>,
    identities: Vec<Digest>,
}

impl Graph {
    /// An empty graph.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            nodes: Vec::new(),
            identities: Vec::new(),
        }
    }

    /// How many nodes there are.
    #[must_use]
    pub fn len(&self) -> usize {
        self.nodes.len()
    }

    /// Whether the graph holds nothing.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.nodes.is_empty()
    }

    /// One node.
    ///
    /// # Errors
    ///
    /// [`RenderStatus::UnknownNode`] if the identifier names nothing.
    pub fn node(&self, id: NodeId) -> Result<&Node> {
        self.nodes.get(id.0).ok_or(RenderStatus::UnknownNode)
    }

    /// Add a node, and return the identifier that names it.
    ///
    /// # Errors
    ///
    /// [`RenderStatus::UnknownNode`] if the node refers to one that does not
    /// exist yet — which is the only way a cycle could be written, and it is
    /// refused here rather than found by a validation pass later.
    /// [`RenderStatus::GraphTooLarge`] past the policy bound.
    pub fn add(&mut self, node: Node) -> Result<NodeId> {
        for input in node.inputs() {
            if input.0 >= self.nodes.len() {
                return Err(RenderStatus::UnknownNode);
            }
        }
        if self.nodes.len() >= MAX_NODES {
            return Err(RenderStatus::GraphTooLarge);
        }
        let identity = self.identity_of(&node)?;
        self.nodes
            .try_reserve(1)
            .map_err(|_| RenderStatus::OutOfMemory)?;
        self.identities
            .try_reserve(1)
            .map_err(|_| RenderStatus::OutOfMemory)?;
        let id = NodeId(self.nodes.len());
        self.nodes.push(node);
        self.identities.push(identity);
        Ok(id)
    }

    /// What a node is, as a digest over its kind, its parameters and the
    /// identities of everything it reads.
    ///
    /// # Errors
    ///
    /// [`RenderStatus::UnknownNode`].
    pub fn identity(&self, id: NodeId) -> Result<Digest> {
        self.identities
            .get(id.0)
            .copied()
            .ok_or(RenderStatus::UnknownNode)
    }

    /// The cache key a node's result is stored under.
    ///
    /// # Errors
    ///
    /// [`RenderStatus::UnknownNode`].
    pub fn cache_key(&self, id: NodeId) -> Result<CacheKey> {
        Ok(CacheKey::current(&[self.identity(id)?], b"render-graph"))
    }

    /// Compute a node's identity from its parts.
    fn identity_of(&self, node: &Node) -> Result<Digest> {
        let mut hasher = Sha256::new();
        hasher.update(b"media-editor-render-node-v1");
        if !absorb_source(&mut hasher, node)? {
            self.absorb_filter(&mut hasher, node)?;
        }
        Ok(hasher.finish())
    }

    /// Absorb a node that reads other nodes.
    ///
    /// Split from [`Graph::identity_of`] along the line the graph is actually
    /// made of: a **source** is named by what it produces and nothing else,
    /// and a **filter** is named by its inputs' identities and its own
    /// parameters. Every filter arm below begins with the same two lines
    /// because of that, and every source arm cannot.
    fn absorb_filter(&self, hasher: &mut Sha256, node: &Node) -> Result<()> {
        match node {
            Node::Convert { input, target } => {
                hasher.update(&[3]);
                hasher.update(self.identity(*input)?.bytes());
                absorb_description(hasher, *target);
            }
            Node::Fade { input, opacity } => {
                hasher.update(&[5]);
                hasher.update(self.identity(*input)?.bytes());
                absorb_rationals(hasher, [*opacity]);
            }
            Node::Wipe {
                input,
                across,
                down,
                fraction,
                softness,
            } => {
                hasher.update(&[9]);
                hasher.update(self.identity(*input)?.bytes());
                absorb_rationals(hasher, [*across, *down, *fraction, *softness]);
            }
            Node::Transform {
                input,
                linear,
                offset,
                anchor,
                bilinear,
            } => {
                hasher.update(&[11]);
                hasher.update(self.identity(*input)?.bytes());
                hasher.update(&[u8::from(*bilinear)]);
                absorb_rationals(
                    hasher,
                    linear
                        .iter()
                        .copied()
                        .chain([offset.0, offset.1, anchor.0, anchor.1]),
                );
            }
            Node::Mask {
                input,
                corners,
                inverted,
            } => {
                hasher.update(&[10]);
                hasher.update(self.identity(*input)?.bytes());
                hasher.update(&[u8::from(*inverted)]);
                absorb_rationals(
                    hasher,
                    corners.iter().flat_map(|corner| [corner.0, corner.1]),
                );
            }
            Node::Associate { input, target } => {
                hasher.update(&[8]);
                hasher.update(self.identity(*input)?.bytes());
                absorb_description(hasher, *target);
            }
            Node::Look {
                input,
                look,
                strength,
            } => {
                hasher.update(&[7]);
                hasher.update(self.identity(*input)?.bytes());
                hasher.update(look.bytes());
                absorb_rationals(hasher, [*strength]);
            }
            Node::Legend { input, text, brief } => {
                hasher.update(&[12]);
                hasher.update(self.identity(*input)?.bytes());
                absorb_text(hasher, text, brief)?;
            }
            Node::Over { layers } => {
                hasher.update(&[6]);
                for layer in layers {
                    hasher.update(self.identity(*layer)?.bytes());
                }
            }
            Node::Pattern { .. }
            | Node::Blank { .. }
            | Node::Empty { .. }
            | Node::Source { .. }
            | Node::Type { .. } => {
                unreachable();
            }
        }
        Ok(())
    }

    /// What a node produces, following the edges where the node cannot say.
    ///
    /// # Errors
    ///
    /// [`RenderStatus::UnknownNode`].
    pub fn description(&self, id: NodeId) -> Result<FrameDescription> {
        let node = self.node(id)?.clone();
        let Some(description) = node.description() else {
            // A fade and an `over` produce whatever their inputs are described
            // as, so follow the first edge. Every input of those two carries
            // the same description — `over` refuses two that differ — so the
            // first one answers for all of them.
            let input = *node.inputs().first().ok_or(RenderStatus::UnknownNode)?;
            return self.description(input);
        };
        Ok(description)
    }

    /// Evaluate one node, using and filling a pool.
    ///
    /// Evaluation is bottom-up over the node's own inputs, which are all
    /// earlier in the graph, so no recursion can run away and no visited set
    /// is needed.
    ///
    /// The pool is what makes this worth building a graph for rather than
    /// calling the operations directly: a node's key is a digest over its
    /// kind, its parameters and its inputs' identities, so a frame that two
    /// parts of a render both need is fetched and computed once. That matters
    /// most for [`Node::Source`], where the cost is a decode.
    ///
    /// # Errors
    ///
    /// [`RenderStatus::UnknownNode`], or any refusal from the work itself.
    pub fn evaluate(
        &self,
        id: NodeId,
        pool: &mut FramePool,
        library: &mut dyn Library,
    ) -> Result<Frame> {
        if let Some(frame) = pool.get(self.cache_key(id)?) {
            return Ok(frame.clone());
        }
        let node = self.node(id)?.clone();
        let frame = match node {
            Node::Pattern {
                pattern,
                description,
            } => pattern.render(description).map_err(RenderStatus::Media)?,
            Node::Blank { description } => {
                Frame::blank(description).map_err(RenderStatus::Media)?
            }
            Node::Empty { description } => nothing(description)?,
            Node::Convert { input, target } => {
                let source = self.evaluate(input, pool, library)?;
                convert::convert(&source, target)?
            }
            Node::Source {
                media: which,
                tick,
                description,
            } => {
                let frame = library.frame(which, tick, description)?;
                if *frame.description() != description {
                    // A source that answers with something other than what it
                    // was asked for has answered a different question, and
                    // converting it here would be a decision made in the wrong
                    // place — `Convert` is a node, with a name (R-1.3).
                    return Err(RenderStatus::SourceDescriptionMismatch);
                }
                frame
            }
            Node::Fade { input, opacity } => {
                let source = self.evaluate(input, pool, library)?;
                composite::faded(&source, opacity)?
            }
            Node::Wipe {
                input,
                across,
                down,
                fraction,
                softness,
            } => {
                let source = self.evaluate(input, pool, library)?;
                let (width, height) = extent(&source)?;
                let coverage =
                    crate::shape::feathered(across, down, fraction, softness, width, height)?;
                composite::masked(&source, &coverage)?
            }
            Node::Transform {
                input,
                linear,
                offset,
                anchor,
                bilinear,
            } => {
                let source = self.evaluate(input, pool, library)?;
                moved(&source, linear, offset, anchor, bilinear)?
            }
            Node::Mask {
                input,
                corners,
                inverted,
            } => {
                let source = self.evaluate(input, pool, library)?;
                let (width, height) = extent(&source)?;
                let coverage = crate::shape::masking(&corners, inverted, width, height)?;
                composite::masked(&source, &coverage)?
            }
            Node::Type { .. } => carded(&node, None)?,
            Node::Legend { input, text, brief } => {
                let source = self.evaluate(input, pool, library)?;
                let placed = extent(&source)?;
                lettered(&source, &text, &brief, placed, None)?
            }
            Node::Associate { input, target } => {
                associated(&self.evaluate(input, pool, library)?, target)?
            }
            Node::Look {
                input,
                look,
                strength,
            } => {
                let source = self.evaluate(input, pool, library)?;
                library.look(look)?.apply(&source, strength)?
            }
            Node::Over { layers } => {
                let bottom = self.evaluate(layers[0], pool, library)?;
                let top = self.evaluate(layers[1], pool, library)?;
                composite::over(&top, &bottom)?
            }
        };
        // A frame too large for the pool is still a correct result; it simply
        // is not kept. Refusing the render because the cache is small would be
        // the cache making a decision that is not its to make.
        match pool.insert(self.cache_key(id)?, frame.clone()) {
            Ok(()) | Err(media_editor_media::MediaStatus::FrameLargerThanPool) => Ok(frame),
            Err(status) => Err(RenderStatus::Media(status)),
        }
    }

    /// Evaluate **one row** of a node, as a frame one row high.
    ///
    /// The same picture as the corresponding row of [`Graph::evaluate`], byte
    /// for byte, computed without ever holding a whole frame. That equality is
    /// the property this exists to have and the thing its tests check for
    /// every node kind at every row.
    ///
    /// ## Why
    ///
    /// A 1920×1080 eight-bit RGBA frame is 8,294,400 bytes and a Phipia
    /// program is mapped 76 KiB, so `evaluate` allocates a hundred and six
    /// times the program's whole address space **per node**. One row of that
    /// frame is 7,680 bytes. The chain below a compositing node is a handful
    /// of rows rather than a handful of frames, which is the difference
    /// between a renderer that cannot run on the target and one that can.
    ///
    /// ## No cache, and that is deliberate
    ///
    /// [`Graph::evaluate`] caches whole frames by node identity. A row
    /// evaluator that did the same would need one entry per node **per row**,
    /// which is the frame it is avoiding, spelled differently. So a row is
    /// computed from its inputs' rows every time.
    ///
    /// That repeats work wherever a node feeds two consumers. In the graphs
    /// this program builds it never does: the planner chains decorations
    /// linearly and combines with `Over`, so the graph is a tree. A future
    /// graph with sharing would pay for it, and would be right to — the
    /// alternative is not paying and not fitting.
    ///
    /// ## What it refuses, and why the two refusals are different
    ///
    /// [`RenderStatus::NotRowLocal`] is about the *operation*:
    /// [`Node::Transform`] resamples, and an output row's preimage is a line
    /// in the source rather than a row. Only a linear map that takes
    /// horizontals to horizontals makes that line one row, and a rotation
    /// never does. A subsampled format is refused the same way and for a
    /// sharper reason: one chroma row serves two luma rows, so a luma row is
    /// not independent of its neighbour.
    ///
    /// [`RenderStatus::NoRowForm`] is about this *build*:
    /// [`Node::Pattern`], [`Node::Type`] and [`Node::Legend`] are generators
    /// whose row form is not written. Somebody reading a refusal needs to know
    /// whether to wait for a later version or to change what they are asking
    /// for, and one status for both would not tell them.
    ///
    /// # Errors
    ///
    /// The two above, [`RenderStatus::OutsideDomain`] for a row outside the
    /// frame, and whatever the operation itself refuses.
    pub fn row(&self, id: NodeId, row: usize, library: &mut dyn Library) -> Result<Frame> {
        let node = self.node(id)?.clone();
        match node {
            Node::Blank { description } => {
                Frame::blank(row_description(description, row)?).map_err(RenderStatus::Media)
            }
            Node::Empty { description } => nothing(row_description(description, row)?),
            Node::Source {
                media: which,
                tick,
                description,
            } => {
                let wanted = row_description(description, row)?;
                let held = library.row(which, tick, description, row)?;
                if *held.description() != wanted {
                    // The same check `evaluate` makes, and for the same
                    // reason: a source that answered a different question has
                    // answered a different question.
                    return Err(RenderStatus::SourceDescriptionMismatch);
                }
                Ok(held)
            }
            Node::Convert { input, target } => {
                let source = self.row(input, row, library)?;
                convert::convert(&source, row_description(target, row)?)
            }
            Node::Fade { input, opacity } => {
                composite::faded(&self.row(input, row, library)?, opacity)
            }
            Node::Associate { input, target } => associated(
                &self.row(input, row, library)?,
                row_description(target, row)?,
            ),
            Node::Look {
                input,
                look,
                strength,
            } => {
                let source = self.row(input, row, library)?;
                library.look(look)?.apply(&source, strength)
            }
            Node::Over { layers } => {
                let bottom = self.row(layers[0], row, library)?;
                let top = self.row(layers[1], row, library)?;
                composite::over(&top, &bottom)
            }
            Node::Mask {
                input,
                corners,
                inverted,
            } => {
                // The geometry first, and the source afterwards. A shape is
                // placed against the whole frame, so a mask over something
                // whose height this cannot know is refused before a row of it
                // is computed -- which is both the cheaper order and the one
                // that gives `described` a reachable answer.
                let (width, height) = self.extent_of(id)?;
                let source = self.row(input, row, library)?;
                let coverage = crate::shape::masking_row(&corners, inverted, width, height, row)?;
                composite::masked(&source, &coverage)
            }
            Node::Wipe {
                input,
                across,
                down,
                fraction,
                softness,
            } => {
                let (width, height) = self.extent_of(id)?;
                let source = self.row(input, row, library)?;
                let coverage = crate::shape::feathered_row(
                    across, down, fraction, softness, width, height, row,
                )?;
                composite::masked(&source, &coverage)
            }
            Node::Transform { .. } => self.banded(&node, (row, row + 1), library),
            Node::Pattern {
                pattern,
                description,
            } => {
                // Placed against the whole picture, one row drawn -- the same
                // discipline a mask takes, because bars are eighths of the
                // width and a checkerboard is counted from the top.
                let _ = row_description(description, row)?;
                let at = u32::try_from(row).map_err(|_| RenderStatus::OutsideDomain)?;
                pattern
                    .render_row(description, at)
                    .map_err(RenderStatus::Media)
            }
            Node::Type { .. } => carded(&node, Some(row)),
            Node::Legend { input, text, brief } => {
                // The geometry before the source, as a mask does: a legend is
                // laid out against the frame it sits on, and one row of that
                // frame cannot say how tall it is.
                let placed = self.extent_of(id)?;
                let source = self.row(input, row, library)?;
                lettered(&source, &text, &brief, placed, Some(row))
            }
        }
    }

    /// Whether every node under this one can be evaluated a row at a time.
    ///
    /// Asked **before** a scan starts rather than discovered during one, which
    /// is the same decision [`Library::available`] makes and for the same
    /// reason: a refusal that arrives at row four hundred has already spent
    /// four hundred rows of work, and a caller that wanted to know whether to
    /// scan or to render whole frames wanted to know *first*.
    ///
    /// The refusal it hands back is the one [`Graph::row`] would have given,
    /// so a caller can tell a transform (which will never scan) from a
    /// generator this build has not written a row form for (which may).
    ///
    /// # Errors
    ///
    /// [`RenderStatus::NotRowLocal`], [`RenderStatus::NoRowForm`], or
    /// [`RenderStatus::UnknownNode`].
    pub fn row_local(&self, id: NodeId) -> Result<()> {
        match self.node(id)? {
            // A description that cannot be cut into rows refuses here as well
            // as at the row itself, so a subsampled programme is turned away
            // before a scan begins rather than at its first row.
            Node::Blank { description } | Node::Empty { description } => {
                row_description(*description, 0).map(|_| ())
            }
            Node::Source { description, .. } => row_description(*description, 0).map(|_| ()),
            Node::Convert { input, target } | Node::Associate { input, target } => {
                row_description(*target, 0)?;
                self.row_local(*input)
            }
            Node::Fade { input, .. }
            | Node::Look { input, .. }
            | Node::Mask { input, .. }
            | Node::Wipe { input, .. }
            | Node::Legend { input, .. } => self.row_local(*input),
            Node::Over { layers } => {
                self.row_local(layers[0])?;
                self.row_local(layers[1])
            }
            Node::Transform { input, .. } => {
                // No question asked of the map, and that is the change strips
                // made. Every invertible transform is scannable now: a scale
                // in one strip, a turn in several. What can still refuse is
                // one *row* of one, and only because its band would be taller
                // than a band may be -- which is a question about a row and
                // not about a graph, so `Graph::row` is where it is answered.
                row_description(self.described(*input)?, 0)?;
                self.row_local(*input)
            }
            // Every generator has a row form now. The description is still
            // checked, because a subsampled card has no rows however well the
            // letters are drawn.
            Node::Pattern { description, .. } | Node::Type { description, .. } => {
                row_description(*description, 0).map(|_| ())
            }
        }
    }

    /// A band of rows of a resampled node, drawn in tiles from bands of its
    /// input's rows.
    ///
    /// The band is asked for **first** and fetched second, so a tile that
    /// cannot be scanned costs nothing and one that can costs exactly the rows
    /// it reads. A map that takes horizontals to horizontals needs one tile
    /// for the whole band; a turn needs several across, because its row's
    /// preimage is a slope and a slope crosses more rows than a band may hold.
    ///
    /// ## Why a band of rows and not one
    ///
    /// Because of what a turn costs otherwise. Drawn a row at a time, strip by
    /// strip, neighbouring strips have overlapping bands and the same source
    /// rows are fetched again for every destination row — about `m · width`
    /// rows for each of `height` rows, where `m` is the slope.
    ///
    /// A tile `h` rows tall fetches its band **once** and draws `h`
    /// destination rows from it, so the whole picture costs about
    /// `m · width · height / h` instead. The saving is the whole of this
    /// milestone and it is exactly the height of the tile.
    ///
    /// ## The width tunes itself
    ///
    /// It starts optimistic — the whole row — and halves whenever
    /// [`crate::resample::tile`] says the band would be too tall, keeping
    /// whatever width worked for the tiles after it. So a scale pays one probe
    /// a band and a turn pays about fourteen once, and neither has to be told
    /// which it is.
    ///
    /// Correctness does not depend on the width at all, and that is what makes
    /// the tuning safe: a tile is a rectangle of columns and rows, not a
    /// different arithmetic, so where the boundaries fall changes nothing
    /// about the pixels.
    ///
    /// It takes the node rather than its five fields, which is what `carded`
    /// settled on for the same reason: five parameters in a fixed order are
    /// five chances to hand a transform somebody else's anchor.
    fn banded(
        &self,
        node: &Node,
        rows: (usize, usize),
        library: &mut dyn Library,
    ) -> Result<Frame> {
        let Node::Transform {
            input,
            linear,
            offset,
            anchor,
            bilinear,
        } = *node
        else {
            return Err(RenderStatus::NotRowLocal);
        };
        let described = self.described(input)?;
        let geometry = described.geometry();
        let mapping = crate::resample::Mapping::about(
            linear,
            offset,
            anchor,
            geometry.width(),
            geometry.height(),
        )?;
        let filter = if bilinear {
            crate::resample::Filter::Bilinear
        } else {
            crate::resample::Filter::Area
        };
        let height = usize::try_from(geometry.height()).map_err(|_| RenderStatus::OutsideDomain)?;
        let width = usize::try_from(geometry.width()).map_err(|_| RenderStatus::OutsideDomain)?;
        if rows.1 > height || rows.0 >= rows.1 {
            return Err(RenderStatus::OutsideDomain);
        }
        let mut out = Vec::new();
        out.try_reserve(rows.1 - rows.0)
            .map_err(|_| RenderStatus::OutOfMemory)?;
        let line = row_description(described, rows.0)?
            .packed_bytes()
            .map_err(RenderStatus::Media)?;
        for _ in rows.0..rows.1 {
            let mut buffer = Vec::new();
            buffer
                .try_reserve(line)
                .map_err(|_| RenderStatus::OutOfMemory)?;
            out.push(buffer);
        }
        let mut wide = width;
        let mut at = 0;
        while at < width {
            let mut span = wide.min(width - at);
            let (from, to) = loop {
                let over = crate::resample::Tile {
                    rows,
                    columns: (at, at + span),
                };
                match crate::resample::tile(mapping, filter, over, height) {
                    Ok(found) => break found,
                    Err(RenderStatus::BandTooTall) if span > 1 => span = span.div_ceil(2),
                    Err(other) => return Err(other),
                }
            };
            wide = span;
            let band = self.gathered(input, from, to, library)?;
            crate::resample::resample_tile(
                band.as_ref(),
                described,
                from,
                mapping,
                filter,
                crate::resample::Tile {
                    rows,
                    columns: (at, at + span),
                },
                &mut out,
            )?;
            at += span;
        }
        let mut packed = Vec::new();
        packed
            .try_reserve(line * (rows.1 - rows.0))
            .map_err(|_| RenderStatus::OutOfMemory)?;
        for buffer in out {
            packed.extend_from_slice(&buffer);
        }
        Ok(Frame::from_owned(
            stacked(described, rows.1 - rows.0)?,
            packed,
        )?)
    }

    /// Rows `from..to` of a node, as one frame that many rows tall, or
    /// nothing at all for an empty range.
    ///
    /// Nothing rather than a refusal, because a destination tile whose
    /// preimage misses the picture asks for an empty band and that is not an
    /// error — there is simply nothing there.
    fn gathered(
        &self,
        input: NodeId,
        from: usize,
        to: usize,
        library: &mut dyn Library,
    ) -> Result<Option<Frame>> {
        if from >= to {
            return Ok(None);
        }
        Ok(Some(self.rows(input, from, to, library)?))
    }

    /// Rows `from..to` of a node, as one frame that many rows tall.
    ///
    /// The band form of [`Graph::row`], and the reason it exists is
    /// [`Node::Transform`]: a turn drawn a row at a time re-reads its source
    /// once per row, and a turn drawn a band at a time reads it once per band.
    /// Everything else here is row-local — its output row is a function of the
    /// same row of its inputs — so for every other node this is the rows,
    /// stacked, and costs exactly what asking for them one at a time would.
    ///
    /// A caller that wants one row asks [`Graph::row`]; a caller that is going
    /// to want all of them asks for as many as it can hold. How many that is
    /// is the caller's to know, which is why there is no bound here:
    /// [`crate::resample::MAX_TILE_ROWS`] says how tall a tile *may* be and
    /// this says nothing about how tall it *should*.
    ///
    /// # Errors
    ///
    /// As [`Graph::row`], plus [`RenderStatus::OutsideDomain`] for an empty or
    /// backwards range.
    pub fn rows(
        &self,
        id: NodeId,
        from: usize,
        to: usize,
        library: &mut dyn Library,
    ) -> Result<Frame> {
        if from >= to {
            return Err(RenderStatus::OutsideDomain);
        }
        let node = self.node(id)?.clone();
        if matches!(node, Node::Transform { .. }) {
            return self.banded(&node, (from, to), library);
        }
        let described = row_description(self.described(id)?, from)?;
        let line = described.packed_bytes().map_err(RenderStatus::Media)?;
        let mut packed = Vec::new();
        packed
            .try_reserve(
                (to - from)
                    .checked_mul(line)
                    .ok_or(RenderStatus::OutsideDomain)?,
            )
            .map_err(|_| RenderStatus::OutOfMemory)?;
        for at in from..to {
            // No check that each row is described the way the band expects,
            // and that absence is deliberate: `row_description` is a function
            // of the node's description and not of the row, so every row of
            // one node carries the same one. A guard here would be a guard
            // whose absence changes no answer, and this project has deleted
            // nine of those. What a row of the wrong *size* would do is refuse
            // at `from_owned` below, on the byte count.
            packed.extend_from_slice(&self.row(id, at, library)?.packed()?);
        }
        Ok(Frame::from_owned(stacked(described, to - from)?, packed)?)
    }

    /// The full geometry a node produces, without producing it.
    ///
    /// A mask and a wipe are placed against the **whole** frame — a shape
    /// stretched over one row is a different shape — so a row of one has to
    /// know how tall the picture it belongs to is. Walking to the description
    /// that decides it is cheaper than rendering the frame to measure it, and
    /// it is the only reason this function exists.
    fn extent_of(&self, id: NodeId) -> Result<(usize, usize)> {
        let geometry = self.described(id)?.geometry();
        Ok((
            usize::try_from(geometry.width()).map_err(|_| RenderStatus::OutsideDomain)?,
            usize::try_from(geometry.height()).map_err(|_| RenderStatus::OutsideDomain)?,
        ))
    }

    /// What a node's frames are described as, found by walking to whatever
    /// says so.
    ///
    /// Every node either carries a description or passes its input's along —
    /// [`Node::Transform`] included, and that is worth a sentence because it
    /// looks like the exception and is not. A transform **resamples into its
    /// source's own description**, so it changes what the picture looks like
    /// and not how large it is, and walking through one gives the right
    /// answer.
    ///
    /// There was a refusal here instead, on the grounds that a transform is
    /// not row-local. Its control could not be made to fail: [`Graph::row`]
    /// refuses the transform itself a moment later with the same status, and
    /// the geometry this returns was correct in the meantime. A guard whose
    /// absence changes no answer is a guard no test can hold — the third time
    /// this project has found one and the third time it has gone.
    fn described(&self, id: NodeId) -> Result<FrameDescription> {
        match self.node(id)? {
            Node::Pattern { description, .. }
            | Node::Blank { description }
            | Node::Empty { description }
            | Node::Source { description, .. }
            | Node::Type { description, .. } => Ok(*description),
            Node::Convert { target, .. } | Node::Associate { target, .. } => Ok(*target),
            // A transform belongs in this arm rather than in one of its own,
            // and clippy is right to say so: it resamples into its source's
            // description, which is the same statement every node here makes.
            Node::Fade { input, .. }
            | Node::Mask { input, .. }
            | Node::Wipe { input, .. }
            | Node::Legend { input, .. }
            | Node::Transform { input, .. }
            | Node::Look { input, .. } => self.described(*input),
            Node::Over { layers } => self.described(layers[0]),
        }
    }
}

/// One row of a description: the same picture, one row high.
///
/// Public because a caller that renders rows has to describe them — an export
/// writing a picture a row at a time needs to know what a row *is* before it
/// asks for one.
///
/// # Errors
///
/// [`RenderStatus::NotRowLocal`] for a subsampled format, where one chroma row
/// serves two luma rows and a luma row is therefore not independent of its
/// neighbour, and [`RenderStatus::OutsideDomain`] for a row outside the frame.
pub fn row_description(description: FrameDescription, row: usize) -> Result<FrameDescription> {
    let geometry = description.geometry();
    if row >= usize::try_from(geometry.height()).map_err(|_| RenderStatus::OutsideDomain)? {
        return Err(RenderStatus::OutsideDomain);
    }
    if description.format().is_subsampled() {
        return Err(RenderStatus::NotRowLocal);
    }
    FrameDescription::new(
        media_editor_media::Geometry::new(geometry.width(), 1).map_err(RenderStatus::Media)?,
        description.format(),
        description.colour(),
        description.siting(),
        description.alpha(),
        description.pixel_aspect(),
    )
    .map_err(RenderStatus::Media)
}

/// The same picture, some number of rows high.
///
/// The other half of [`row_description`]: that one cuts a picture into rows
/// and this one says what a stack of them is described as.
///
/// # Errors
///
/// [`RenderStatus::Media`] for a height that is not a geometry.
fn stacked(described: FrameDescription, rows: usize) -> Result<FrameDescription> {
    FrameDescription::new(
        media_editor_media::Geometry::new(
            described.geometry().width(),
            u32::try_from(rows).map_err(|_| RenderStatus::OutsideDomain)?,
        )
        .map_err(RenderStatus::Media)?,
        described.format(),
        described.colour(),
        described.siting(),
        described.alpha(),
        described.pixel_aspect(),
    )
    .map_err(RenderStatus::Media)
}

/// A frame of no light and no coverage.
///
/// The other nothing, and which one a graph asks for is the whole of the
/// difference. [`Node::Blank`] is the opaque black a *programme* shows where
/// it has nothing — a viewer displays black leader and an export writes black
/// frames. This is what *material* looks like where it has nothing, and a
/// nested sequence composited onto black would blank out every track beneath
/// it wherever it happened to be empty.
///
/// # Errors
///
/// [`RenderStatus::Media`] wrapping whatever the frame types refuse — which
/// includes a format with no coverage, since absence needs somewhere to be
/// said.
fn nothing(description: FrameDescription) -> Result<Frame> {
    Frame::clear(description).map_err(RenderStatus::Media)
}

/// A frame with its coverage associated the other way.
///
/// Anything but the two real directions is refused: a frame with no coverage
/// has nothing to associate, and a node asking for the state its input is
/// already in is claiming to change something it is not changing.
fn associated(source: &Frame, target: FrameDescription) -> Result<Frame> {
    match (source.description().alpha(), target.alpha()) {
        (Some(AlphaState::Straight), Some(AlphaState::Premultiplied)) => {
            composite::premultiply(source)
        }
        (Some(AlphaState::Premultiplied), Some(AlphaState::Straight)) => {
            composite::unpremultiply(source)
        }
        _ => Err(RenderStatus::WrongAlphaState),
    }
}

/// A frame resampled through a transform about its own centre.
fn moved(
    source: &Frame,
    linear: [Rational; 4],
    offset: (Rational, Rational),
    anchor: (Rational, Rational),
    bilinear: bool,
) -> Result<Frame> {
    let described = *source.description();
    let geometry = described.geometry();
    let mapping = crate::resample::Mapping::about(
        linear,
        offset,
        anchor,
        geometry.width(),
        geometry.height(),
    )?;
    crate::resample::resample(
        source,
        described,
        mapping,
        if bilinear {
            crate::resample::Filter::Bilinear
        } else {
            crate::resample::Filter::Area
        },
    )
}

/// A frame with a caption set across it, or the frame unchanged.
///
/// White type, centred, on a baseline two thirds of the way down, at whatever
/// size lets the run fit the width with a margin — capped so a short caption
/// on a wide frame does not become a billboard.
///
/// The type is built **straight** and premultiplied by the same conversion
/// every other layer goes through, rather than by writing the coverage into
/// all four channels. Those two are not the same thing: a premultiplied sample
/// is the colour times the coverage *in light*, and code values are not light.
/// Writing the coverage byte into the colour would draw type that is too dark
/// at every edge, everywhere, by exactly the amount the transfer curve bends —
/// which is the same mistake the compositor was built to stop making.
fn lettered(
    source: &Frame,
    text: &str,
    brief: &str,
    placed: (usize, usize),
    row: Option<usize>,
) -> Result<Frame> {
    // The extent the *legend* is placed against, which is the whole frame even
    // when the source handed over is one row of it.
    let (width, height) = placed;
    let mut chosen = crate::font::caption(text, width, height)?;
    if chosen.is_none() {
        chosen = crate::font::caption(brief, width, height)?;
    }
    let Some(run) = chosen else {
        // Too small even for the short one. The stripes underneath already say
        // the one thing that matters, and a grey smear would say it less well.
        return Ok(source.clone());
    };
    let coverage = match row {
        None => run.plane(width, height)?,
        Some(row) => run.plane_row(width, height, row)?,
    };
    let described = source.description();
    let straight = described
        .with_alpha(AlphaState::Straight)
        .map_err(RenderStatus::Media)?;
    let mut packed = alloc::vec::Vec::new();
    packed
        .try_reserve(
            coverage
                .len()
                .checked_mul(4)
                .ok_or(RenderStatus::OutOfMemory)?,
        )
        .map_err(|_| RenderStatus::OutOfMemory)?;
    // Full light, spelled the way this frame spells it. A hard-coded 255 is
    // an *illegal* code value in limited range, which some equipment reads as
    // a sync pattern -- so even a caption nobody chose the colour of has to
    // ask the table what white is.
    let white = crate::convert::TransferTable::build(straight.colour())?.encode(Fixed::ONE);
    for alpha in &coverage {
        packed.extend_from_slice(&[white, white, white, *alpha]);
    }
    let letters = Frame::from_owned(straight, packed).map_err(RenderStatus::Media)?;
    composite::over(&composite::premultiply(&letters)?, source)
}

/// Set a card, whole or one row of it.
///
/// One door for both forms, so a card and a row of a card cannot disagree
/// about where a letter falls. The node is matched here rather than at each
/// call site because a card carries seven fields and naming them twice is
/// seven chances to name one wrongly.
///
/// # Errors
///
/// [`RenderStatus::UnknownNode`] for a node that is not a card, and whatever
/// setting one refuses.
fn carded(node: &Node, row: Option<usize>) -> Result<Frame> {
    let Node::Type {
        description,
        lines,
        size,
        across,
        down,
        alignment,
        ink,
    } = node
    else {
        return Err(RenderStatus::UnknownNode);
    };
    let geometry = description.geometry();
    let width = usize::try_from(geometry.width()).map_err(|_| RenderStatus::OutsideDomain)?;
    let height = usize::try_from(geometry.height()).map_err(|_| RenderStatus::OutsideDomain)?;
    let borrowed: alloc::vec::Vec<&str> = lines.iter().map(alloc::string::String::as_str).collect();
    // Placed against the **whole** frame either way: the em is a fraction of
    // the height and the pen starts at a fraction of the width, so a card
    // typeset into one row would be a different card.
    let run = crate::font::title(&borrowed, *size, *across, *down, *alignment, width, height)?;
    let coverage = match row {
        None => run.plane(width, height)?,
        Some(row) => run.plane_row(width, height, row)?,
    };
    let out = match row {
        None => *description,
        Some(row) => row_description(*description, row)?,
    };
    let straight = out
        .with_alpha(AlphaState::Straight)
        .map_err(RenderStatus::Media)?;
    let mut packed = alloc::vec::Vec::new();
    packed
        .try_reserve(
            coverage
                .len()
                .checked_mul(4)
                .ok_or(RenderStatus::OutOfMemory)?,
        )
        .map_err(|_| RenderStatus::OutOfMemory)?;
    let table = crate::convert::TransferTable::build(straight.colour())?;
    let mut colour = [0_u8; 3];
    for (slot, channel) in colour.iter_mut().zip(*ink) {
        *slot = table.encode(Fixed::from_rational(channel)?);
    }
    for alpha in &coverage {
        packed.extend_from_slice(&[colour[0], colour[1], colour[2], *alpha]);
    }
    let letters = Frame::from_owned(straight, packed).map_err(RenderStatus::Media)?;
    let associated = composite::premultiply(&letters)?;
    if out.alpha() == Some(AlphaState::Premultiplied) {
        Ok(associated)
    } else {
        // A description that asks for straight coverage gets it, rather than a
        // frame labelled one way and holding the other.
        composite::unpremultiply(&associated)
    }
}

/// A frame's size, as the counts a rasteriser wants.
fn extent(frame: &Frame) -> Result<(usize, usize)> {
    let geometry = frame.description().geometry();
    Ok((
        usize::try_from(geometry.width()).map_err(|_| RenderStatus::OutsideDomain)?,
        usize::try_from(geometry.height()).map_err(|_| RenderStatus::OutsideDomain)?,
    ))
}

/// Absorb a node that reads nothing, saying whether it was one.
///
/// A source is named by what it produces: a pattern by which pattern, a title
/// by what it says. None of them has an input to fold in, which is exactly
/// what makes them sources.
fn absorb_source(hasher: &mut Sha256, node: &Node) -> Result<bool> {
    match node {
        Node::Pattern {
            pattern,
            description,
        } => {
            hasher.update(&[1]);
            absorb_pattern(hasher, *pattern);
            absorb_description(hasher, *description);
        }
        Node::Blank { description } => {
            hasher.update(&[2]);
            absorb_description(hasher, *description);
        }
        Node::Empty { description } => {
            // Its own tag, and not a variation on the blank's. Two nodes that
            // draw different pictures must be two keys, and black and absence
            // are as different as two pictures get.
            hasher.update(&[13]);
            absorb_description(hasher, *description);
        }
        Node::Source {
            media,
            tick,
            description,
        } => {
            hasher.update(&[4]);
            hasher.update(media.bytes());
            hasher.update(&tick.to_le_bytes());
            absorb_description(hasher, *description);
        }
        Node::Type {
            description,
            lines,
            size,
            across,
            down,
            alignment,
            ink,
        } => {
            hasher.update(&[13]);
            absorb_description(hasher, *description);
            hasher.update(
                &u64::try_from(lines.len())
                    .map_err(|_| RenderStatus::OutsideDomain)?
                    .to_le_bytes(),
            );
            for line in lines {
                absorb_text(hasher, line, "")?;
            }
            hasher.update(&[match alignment {
                crate::font::Alignment::Left => 0,
                crate::font::Alignment::Centre => 1,
                crate::font::Alignment::Right => 2,
            }]);
            absorb_rationals(hasher, [*size, *across, *down]);
            absorb_rationals(hasher, *ink);
        }
        _ => return Ok(false),
    }
    Ok(true)
}

/// A match arm the shape of the type makes impossible.
///
/// Not a panic and not a refusal that could be mistaken for a real one: the
/// two halves of a node's identity partition the node kinds, and this is the
/// half of each partition the other one covers.
const fn unreachable() {}

/// Absorb exact numbers into a hash, each as its two halves.
///
/// Both halves rather than one scaled integer, for the reason the project file
/// writes them the same way: a third is a third, and a node keyed by a decimal
/// near it would be a node that two builds disagreed about.
fn absorb_rationals(hasher: &mut Sha256, values: impl IntoIterator<Item = Rational>) {
    for held in values {
        hasher.update(&held.numerator().to_le_bytes());
        hasher.update(&held.denominator().to_le_bytes());
    }
}

/// Absorb a legend's two captions into a hash, each length first.
///
/// The length before the bytes, so two captions cannot run together into one
/// digest: "AB" then "C" and "A" then "BC" are different slates and have to be
/// different keys.
fn absorb_text(hasher: &mut Sha256, text: &str, brief: &str) -> Result<()> {
    for held in [text, brief] {
        hasher.update(
            &u64::try_from(held.len())
                .map_err(|_| RenderStatus::OutsideDomain)?
                .to_le_bytes(),
        );
        hasher.update(held.as_bytes());
    }
    Ok(())
}

/// Absorb a pattern's identity into a hash.
fn absorb_pattern(hasher: &mut Sha256, pattern: TestPattern) {
    match pattern {
        TestPattern::Bars => hasher.update(&[1]),
        TestPattern::Ramp => hasher.update(&[2]),
        TestPattern::Checkerboard { square } => {
            hasher.update(&[3]);
            hasher.update(&square.to_le_bytes());
        }
        TestPattern::Flat { value } => {
            hasher.update(&[4, value]);
        }
        TestPattern::Offline => hasher.update(&[5]),
    }
}

/// Absorb a description's identity into a hash.
fn absorb_description(hasher: &mut Sha256, description: FrameDescription) {
    hasher.update(&description.geometry().width().to_le_bytes());
    hasher.update(&description.geometry().height().to_le_bytes());
    hasher.update(&description.pixel_aspect().numerator().to_le_bytes());
    hasher.update(&description.pixel_aspect().denominator().to_le_bytes());
    // The format and the colour go in through the frame's own tagging, which
    // already has stable numbers for them: a blank frame of this description
    // is a value whose digest covers exactly these things.
    match Frame::blank(description) {
        Ok(frame) => hasher.update(frame.digest().bytes()),
        Err(_) => hasher.update(b"undescribable"),
    }
}

/// The description a colour conversion of a node would produce, for callers
/// building a graph who want to check before they add.
#[must_use]
pub fn converted_description(
    source: FrameDescription,
    colour: ColourDescription,
) -> Option<FrameDescription> {
    FrameDescription::new(
        source.geometry(),
        source.format(),
        colour,
        source.siting(),
        source.alpha(),
        source.pixel_aspect(),
    )
    .ok()
}
