// SPDX-License-Identifier: GPL-3.0-only
//! Compositing, against what the operator is supposed to mean.
//!
//! `over` is an algebra before it is a loop: an identity on each side, an
//! absorbing element, and associativity. Those are checked here as algebra,
//! and the one property that eight-bit arithmetic cannot deliver exactly is
//! measured rather than asserted away.

use media_editor_media::colour::{MatrixCoefficients, Primaries, Range, TransferFunction};
use media_editor_media::{
    AlphaState, ColourDescription, Frame, FrameDescription, Geometry, PixelFormat,
};
use media_editor_render::composite::{checked_premultiplied, over, premultiply, unpremultiply};
use media_editor_render::{RenderStatus, convert};

/// The colour every test here works in unless it says otherwise.
fn srgb() -> ColourDescription {
    ColourDescription::srgb_full()
}

fn described(width: u32, height: u32, state: AlphaState) -> FrameDescription {
    FrameDescription::square(
        Geometry::new(width, height).expect("a geometry"),
        PixelFormat::Rgba8,
        srgb(),
        None,
        Some(state),
    )
    .expect("a description")
}

/// A frame from a list of `(r, g, b, a)` pixels.
fn frame(pixels: &[(u8, u8, u8, u8)], state: AlphaState) -> Frame {
    let width = u32::try_from(pixels.len()).expect("a width");
    let mut bytes = std::vec::Vec::new();
    for &(red, green, blue, alpha) in pixels {
        bytes.extend_from_slice(&[red, green, blue, alpha]);
    }
    Frame::from_packed(described(width, 1, state), &bytes).expect("a frame")
}

/// A frame's pixels, back out.
fn pixels(frame: &Frame) -> std::vec::Vec<(u8, u8, u8, u8)> {
    frame
        .to_packed()
        .expect("packed bytes")
        .chunks_exact(4)
        .map(|pixel| (pixel[0], pixel[1], pixel[2], pixel[3]))
        .collect()
}

/// A deterministic spread of pixels that are valid premultiplied samples.
///
/// Generated by premultiplying straight ones, which is the only way to be sure
/// they are valid — inventing premultiplied samples directly is how a test
/// ends up asserting something the operator never has to handle.
fn premultiplied_spread(seed: u64) -> Frame {
    let mut state = seed;
    let mut straight = std::vec::Vec::new();
    for _ in 0..64 {
        let mut next = || {
            // A small LCG: reproducible on every machine, and not floating
            // point (R-4.1).
            state = state
                .wrapping_mul(6_364_136_223_846_793_005)
                .wrapping_add(1);
            u8::try_from((state >> 33) & 0xFF).unwrap_or(0)
        };
        straight.push((next(), next(), next(), next()));
    }
    premultiply(&frame(&straight, AlphaState::Straight)).expect("premultiplied")
}

#[test]
fn a_transparent_layer_over_anything_leaves_it_alone() {
    // The identity on the left. Zero coverage contributes no light and no
    // coverage, so every sample of the result must be the bottom layer's, bit
    // for bit — not nearly, exactly.
    let bottom = premultiplied_spread(1);
    let clear = frame(&[(0, 0, 0, 0); 64], AlphaState::Premultiplied);
    let result = over(&clear, &bottom).expect("a composite");
    assert_eq!(result.digest(), bottom.digest());
    assert_eq!(result, bottom);
}

#[test]
fn an_opaque_layer_over_anything_hides_it() {
    // The absorbing element. Full coverage leaves no remainder, so the bottom
    // layer cannot contribute anything at all.
    let bottom = premultiplied_spread(2);
    let top = frame(&[(200, 30, 90, 255); 64], AlphaState::Premultiplied);
    let result = over(&top, &bottom).expect("a composite");
    assert_eq!(result, top);
    assert_eq!(
        over(&top, &frame(&[(0, 0, 0, 0); 64], AlphaState::Premultiplied)).expect("a composite"),
        top,
        "and over nothing, the same"
    );
}

#[test]
fn compositing_over_an_opaque_layer_gives_an_opaque_result() {
    // Nothing may become see-through by having something laid on it. This is
    // what makes a background a background.
    let opaque =
        premultiply(&frame(&[(10, 20, 30, 255); 64], AlphaState::Straight)).expect("premultiplied");
    let top = premultiplied_spread(3);
    let result = over(&top, &opaque).expect("a composite");
    for pixel in pixels(&result) {
        assert_eq!(pixel.3, 255, "{pixel:?}");
    }
}

#[test]
fn a_half_covered_white_is_composited_in_light_and_not_in_code_values() {
    // Worked out by hand, and worked out over a background that can tell the
    // difference. Over black it could not: the background contributes nothing
    // either way, so compositing in the encoded space would give the same
    // answer and this test would pass against the bug it exists to catch.
    //
    // So: full white at coverage 128, over an opaque sRGB mid-grey.
    //
    //   top light      = 128/255                       = 0.501961
    //   bottom light   = ((128/255 + 0.055)/1.055)^2.4 = 0.215861
    //   remainder      = 1 - 128/255                   = 0.498039
    //   result light   = 0.501961 + 0.215861 x 0.498039 = 0.609468
    //   sRGB of that   = 1.055 x 0.609468^(1/2.4) - 0.055 = 0.803319
    //   code value     = 0.803319 x 255                 = 204.85 -> 205
    //
    // Adding the code values instead — 188 and 128 — gives 252, which is
    // forty-seven code values too bright and is precisely what a compositor
    // that skips the transfer function produces.
    let top =
        premultiply(&frame(&[(255, 255, 255, 128)], AlphaState::Straight)).expect("premultiplied");
    assert_eq!(
        pixels(&top)[0],
        (188, 188, 188, 128),
        "premultiplying happens in light too: 128/255 of full white encodes \
         to 188, not to 128"
    );

    let grey = frame(&[(128, 128, 128, 255)], AlphaState::Premultiplied);
    let result = over(&top, &grey).expect("a composite");
    assert_eq!(pixels(&result)[0], (205, 205, 205, 255));
}

#[test]
fn compositing_straight_samples_as_premultiplied_is_the_dark_fringe() {
    // The bug itself, demonstrated rather than described. A half-covered white
    // edge over a black background: done correctly the edge is mid-grey; done
    // by relabelling straight samples as premultiplied it comes out far too
    // bright, and over a white background the same mistake comes out far too
    // dark. That asymmetry is why the artefact is called a fringe: it takes
    // the colour of whichever mistake the background makes.
    let straight = frame(&[(255, 255, 255, 128)], AlphaState::Straight);
    let honest = premultiply(&straight).expect("premultiplied");
    let black = frame(&[(0, 0, 0, 255)], AlphaState::Premultiplied);
    let correct = pixels(&over(&honest, &black).expect("a composite"))[0];

    // Now the mistake: call the straight samples premultiplied and composite
    // them. The operator refuses, which is the whole point of the check —
    // white at half coverage is brighter than half coverage allows.
    let relabelled = Frame::from_packed(
        described(1, 1, AlphaState::Premultiplied),
        &straight.to_packed().expect("bytes"),
    )
    .expect("a frame");
    assert_eq!(
        over(&relabelled, &black),
        Err(RenderStatus::NotPremultiplied),
        "a frame whose colour outruns its coverage is not premultiplied, \
         whatever its description says"
    );

    // And if it were not refused, this is what it would produce: the top
    // layer's full-strength white plus the background's remainder, which is
    // brighter than the correct answer by a wide margin.
    let (red, _, _, _) = correct;
    assert!(
        red < 255,
        "the correct half-covered white is not full white; the relabelled \
         one would be"
    );
}

#[test]
fn a_frame_that_is_not_premultiplied_is_caught_and_a_real_one_is_not() {
    let straight = frame(&[(255, 200, 100, 8); 16], AlphaState::Straight);
    let honest = premultiply(&straight).expect("premultiplied");
    checked_premultiplied(&honest).expect("an honest frame passes");

    let relabelled = Frame::from_packed(
        described(16, 1, AlphaState::Premultiplied),
        &straight.to_packed().expect("bytes"),
    )
    .expect("a frame");
    assert_eq!(
        checked_premultiplied(&relabelled),
        Err(RenderStatus::NotPremultiplied)
    );

    // Every frame this module produces must pass its own check, or the
    // operator is not closed over its own output.
    for seed in 1..8 {
        let spread = premultiplied_spread(seed);
        checked_premultiplied(&spread).expect("a generated frame passes");
        let stacked = over(&spread, &premultiplied_spread(seed + 100)).expect("a composite");
        checked_premultiplied(&stacked).expect("a composed frame passes");
    }
}

#[test]
fn over_is_associative_to_within_one_code_value() {
    // In exact arithmetic `over` is associative, which is what makes a layer
    // stack a stack rather than an order of operations. In eight bits it is
    // associative to within quantisation, and this measures the gap rather
    // than assuming it: three layers, both groupings, worst channel over four
    // thousand samples.
    //
    // If the two groupings could differ by more than a code value, a layer
    // stack would change its picture when a user grouped two clips into a
    // compound — and that is a bug report nobody could ever reproduce.
    let mut worst = 0_i32;
    for seed in 1..16 {
        let first = premultiplied_spread(seed);
        let second = premultiplied_spread(seed + 40);
        let third = premultiplied_spread(seed + 80);

        let left = over(&over(&first, &second).expect("a composite"), &third).expect("a composite");
        let right =
            over(&first, &over(&second, &third).expect("a composite")).expect("a composite");

        for (one, other) in pixels(&left).iter().zip(pixels(&right).iter()) {
            for (a, b) in [
                (one.0, other.0),
                (one.1, other.1),
                (one.2, other.2),
                (one.3, other.3),
            ] {
                worst = worst.max((i32::from(a) - i32::from(b)).abs());
            }
        }
    }
    assert!(
        worst <= 1,
        "the two groupings differ by {worst} code values, which is more than \
         quantisation can account for"
    );
}

#[test]
fn premultiplying_and_dividing_back_out_is_exact_only_at_full_coverage() {
    // The honest statement of a lossy round trip. At full coverage nothing was
    // multiplied away, so every sample must come back exactly. Below it,
    // precision was discarded and cannot return, so the claim is a bound and
    // the bound is measured.
    let opaque: std::vec::Vec<(u8, u8, u8, u8)> = (0..64)
        .map(|index| (index * 4, 255 - index * 4, 128, 255))
        .collect();
    let straight = frame(&opaque, AlphaState::Straight);
    let back = unpremultiply(&premultiply(&straight).expect("premultiplied")).expect("straight");
    assert_eq!(back, straight, "full coverage multiplies by one");

    // Half coverage: recoverable to within a code value or two, because the
    // multiply threw away a bit and the divide is amplifying what is left.
    let half: std::vec::Vec<(u8, u8, u8, u8)> = (0..64)
        .map(|index| (index * 4, 255 - index * 4, 128, 128))
        .collect();
    let straight = frame(&half, AlphaState::Straight);
    let back = unpremultiply(&premultiply(&straight).expect("premultiplied")).expect("straight");
    let mut worst = 0_i32;
    for (one, other) in pixels(&back).iter().zip(half.iter()) {
        for (a, b) in [(one.0, other.0), (one.1, other.1), (one.2, other.2)] {
            worst = worst.max((i32::from(a) - i32::from(b)).abs());
        }
        assert_eq!(one.3, other.3, "coverage itself is never lost");
    }
    assert!(
        worst <= 2,
        "half-coverage round trip lost {worst} code values"
    );
}

#[test]
fn zero_coverage_keeps_no_colour_at_all() {
    // Multiplying by zero is not lossy, it is total. The colour is gone, and
    // pretending otherwise — carrying the straight value along beside a zero
    // alpha — is how a fully transparent pixel ends up contributing a colour
    // fringe when something later scales the picture.
    let straight = frame(&[(255, 128, 64, 0); 8], AlphaState::Straight);
    let premultiplied = premultiply(&straight).expect("premultiplied");
    for pixel in pixels(&premultiplied) {
        assert_eq!(pixel, (0, 0, 0, 0));
    }
    for pixel in pixels(&unpremultiply(&premultiplied).expect("straight")) {
        assert_eq!(pixel, (0, 0, 0, 0), "nothing was kept, so nothing returns");
    }
}

#[test]
fn compositing_is_deterministic() {
    let top = premultiplied_spread(5);
    let bottom = premultiplied_spread(6);
    let first = over(&top, &bottom).expect("a composite");
    let second = over(&top, &bottom).expect("a composite");
    assert_eq!(first.digest(), second.digest());
    assert_eq!(
        premultiply(&frame(&[(1, 2, 3, 4); 4], AlphaState::Straight))
            .expect("premultiplied")
            .digest(),
        premultiply(&frame(&[(1, 2, 3, 4); 4], AlphaState::Straight))
            .expect("premultiplied")
            .digest()
    );
}

#[test]
fn a_format_without_alpha_cannot_be_composited() {
    let opaque = FrameDescription::square(
        Geometry::new(4, 4).expect("a geometry"),
        PixelFormat::Rgb8,
        srgb(),
        None,
        None,
    )
    .expect("a description");
    let plain = Frame::blank(opaque).expect("a frame");
    assert_eq!(premultiply(&plain), Err(RenderStatus::AlphaRequired));
    assert_eq!(unpremultiply(&plain), Err(RenderStatus::AlphaRequired));
    assert_eq!(over(&plain, &plain), Err(RenderStatus::AlphaRequired));
    assert_eq!(
        checked_premultiplied(&plain),
        Err(RenderStatus::AlphaRequired)
    );
}

#[test]
fn the_two_alpha_states_are_not_interchangeable() {
    let straight = frame(&[(10, 20, 30, 200); 4], AlphaState::Straight);
    let premultiplied = premultiply(&straight).expect("premultiplied");
    assert_eq!(
        premultiply(&premultiplied),
        Err(RenderStatus::WrongAlphaState),
        "multiplying twice is not a thing that can be asked for"
    );
    assert_eq!(
        unpremultiply(&straight),
        Err(RenderStatus::WrongAlphaState),
        "nor is dividing out what was never multiplied in"
    );
    assert_eq!(
        over(&straight, &straight),
        Err(RenderStatus::WrongAlphaState),
        "and `over` on straight samples is the bug, not an option"
    );
}

#[test]
fn two_frames_that_are_not_the_same_picture_are_not_layers() {
    // Different geometry, different colour, different pixel aspect: each is a
    // decision somebody has to make before these can be added, and none of
    // them is this operator's to make silently.
    let top = premultiply(&frame(&[(1, 2, 3, 200); 8], AlphaState::Straight)).expect("a frame");

    let narrower =
        premultiply(&frame(&[(1, 2, 3, 200); 4], AlphaState::Straight)).expect("a frame");
    assert_eq!(over(&top, &narrower), Err(RenderStatus::NotComposable));

    let wide = FrameDescription::square(
        Geometry::new(8, 1).expect("a geometry"),
        PixelFormat::Rgba8,
        ColourDescription::new(
            Primaries::Bt2020,
            TransferFunction::PerceptualQuantiser,
            MatrixCoefficients::Identity,
            Range::Full,
        ),
        None,
        Some(AlphaState::Premultiplied),
    )
    .expect("a description");
    let other = Frame::from_packed(wide, &top.to_packed().expect("bytes")).expect("a frame");
    assert_eq!(over(&top, &other), Err(RenderStatus::NotComposable));
}

/// The worst disagreement permitted between the sRGB and the linear route, in
/// each band of 32 sRGB code values. Measured, not guessed: above the midpoint
/// the two routes agree to within a single code value; below it, eight-bit
/// linear runs out of steps.
const BOUND: [i32; 8] = [11, 5, 3, 2, 1, 1, 1, 1];

#[test]
fn compositing_works_in_light_whatever_the_frames_are_encoded_in() {
    // The same two layers, composited in sRGB and in linear, must produce the
    // same *light*. The encodings differ, so the code values must too, but
    // converting one result into the other's description has to land on it.
    // That is what "in linear light and nowhere else" means as a property
    // rather than a slogan: the answer does not depend on the encoding it
    // happened to arrive in.
    //
    // It does not land exactly, and the reason is worth measuring rather than
    // hiding behind one loose tolerance. Eight-bit *linear* has 255 evenly
    // spaced steps of light, and sRGB spends most of its code values in the
    // shadows precisely because the eye does. So the round trip through linear
    // is faithful in the highlights and coarse near black — and the error is
    // bounded per brightness band, which is a statement about the format
    // rather than about this operator.
    let linear_colour = ColourDescription::new(
        Primaries::Bt709,
        TransferFunction::Linear,
        MatrixCoefficients::Identity,
        Range::Full,
    );
    let linear_description = FrameDescription::square(
        Geometry::new(64, 1).expect("a geometry"),
        PixelFormat::Rgba8,
        linear_colour,
        None,
        Some(AlphaState::Premultiplied),
    )
    .expect("a description");

    let mut worst = [0_i32; 8];

    for seed in 11..20 {
        let top = premultiplied_spread(seed);
        let bottom = premultiplied_spread(seed + 40);
        let in_srgb = over(&top, &bottom).expect("a composite");

        let in_linear = over(
            &convert(&top, linear_description).expect("converted"),
            &convert(&bottom, linear_description).expect("converted"),
        )
        .expect("a composite");

        assert_ne!(
            in_srgb.to_packed().expect("bytes"),
            in_linear.to_packed().expect("bytes"),
            "different encodings hold different code values, or this test is \
             comparing a thing with itself"
        );

        let brought_back = convert(&in_linear, *in_srgb.description()).expect("converted");
        for (one, other) in pixels(&brought_back).iter().zip(pixels(&in_srgb).iter()) {
            assert_eq!(one.3, other.3, "coverage survives a conversion unchanged");
            for (mine, theirs) in [(one.0, other.0), (one.1, other.1), (one.2, other.2)] {
                let band = usize::from(theirs) / 32;
                worst[band] = worst[band].max((i32::from(mine) - i32::from(theirs)).abs());
            }
        }
    }

    for (band, (seen, allowed)) in worst.iter().zip(BOUND.iter()).enumerate() {
        assert!(
            seen <= allowed,
            "sRGB codes {}..{} disagree by {seen}, past the {allowed} that \
             eight-bit linear accounts for",
            band * 32,
            band * 32 + 31
        );
    }
    assert!(
        worst[4..].iter().all(|seen| *seen <= 1),
        "above the midpoint the two routes must agree to a code value: {worst:?}"
    );
    assert!(
        worst[0] > worst[7],
        "if the shadows were not the coarse end, this test would be measuring \
         something other than what it claims"
    );
}

#[test]
fn a_conversion_will_not_quietly_change_what_alpha_means() {
    // Gaining alpha, losing it, and re-associating it are three operations
    // with three names. A colour conversion that did any of them silently is
    // how a keyed title arrives opaque — which is exactly what this codebase
    // did until this test was written.
    let premultiplied = premultiplied_spread(21);
    let straight = FrameDescription::square(
        Geometry::new(64, 1).expect("a geometry"),
        PixelFormat::Rgba8,
        srgb(),
        None,
        Some(AlphaState::Straight),
    )
    .expect("a description");
    assert_eq!(
        convert(&premultiplied, straight),
        Err(RenderStatus::ConversionUnavailable),
        "re-associating alpha is `premultiply`'s job, and it has a name"
    );

    let opaque = FrameDescription::square(
        Geometry::new(64, 1).expect("a geometry"),
        PixelFormat::Rgb8,
        srgb(),
        None,
        None,
    )
    .expect("a description");
    assert_eq!(
        convert(&premultiplied, opaque),
        Err(RenderStatus::ConversionUnavailable),
        "dropping coverage is compositing against a background, and that has \
         a name too"
    );
}

#[test]
fn a_conversion_carries_coverage_through_untouched() {
    // Coverage is not light: no transfer function, no gamut matrix, no
    // limited-range scaling. Every alpha byte must arrive on the other side
    // exactly as it left, including the ones that are neither 0 nor 255.
    let source = premultiplied_spread(22);
    let wide = FrameDescription::square(
        Geometry::new(64, 1).expect("a geometry"),
        PixelFormat::Rgba8,
        ColourDescription::new(
            Primaries::Bt2020,
            TransferFunction::PerceptualQuantiser,
            MatrixCoefficients::Identity,
            Range::Full,
        ),
        None,
        Some(AlphaState::Premultiplied),
    )
    .expect("a description");
    let converted = convert(&source, wide).expect("converted");

    let before: std::vec::Vec<u8> = pixels(&source).iter().map(|pixel| pixel.3).collect();
    let after: std::vec::Vec<u8> = pixels(&converted).iter().map(|pixel| pixel.3).collect();
    assert_eq!(before, after);
    assert!(
        before.iter().any(|alpha| *alpha != 0 && *alpha != 255),
        "a test that only saw opaque and clear pixels would have passed \
         against the bug it exists to catch"
    );
    assert_ne!(
        source.to_packed().expect("bytes"),
        converted.to_packed().expect("bytes"),
        "the colour did change, so the alpha was carried rather than skipped"
    );
}

#[test]
fn the_premultiplied_tolerance_is_exactly_one_code_value() {
    // The check allows a re-encoded sample one code value past its exact
    // bound, because changing encodings can move it that far. That tolerance
    // is pinned from both sides here: one over passes, two over does not. A
    // tolerance nobody tests is a tolerance that grows.
    //
    // Coverage 128 in sRGB: the light is 128/255 = 0.50196, and the sRGB code
    // nearest that light is 188. So 189 is the last sample this accepts.
    let ceiling = 188_u8;
    for (offset, accepted) in [(0_u8, true), (1, true), (2, false)] {
        let value = ceiling + offset;
        let candidate = frame(&[(value, 0, 0, 128)], AlphaState::Premultiplied);
        assert_eq!(
            checked_premultiplied(&candidate).is_ok(),
            accepted,
            "a sample {offset} code values past the ceiling"
        );
    }

    // And the bug it exists to catch misses by far more than one.
    let white = frame(&[(255, 255, 255, 128)], AlphaState::Premultiplied);
    assert_eq!(
        checked_premultiplied(&white),
        Err(RenderStatus::NotPremultiplied),
        "full white at half coverage is {} code values past its ceiling",
        255 - ceiling
    );
}

/// A frame of one colour at one coverage, premultiplied, of a given size.
fn flat(width: u32, height: u32, sample: [u8; 4]) -> Frame {
    let description = described(width, height, AlphaState::Premultiplied);
    let mut packed = std::vec::Vec::new();
    for _ in 0..(width as usize * height as usize) {
        packed.extend_from_slice(&sample);
    }
    Frame::from_packed(description, &packed).expect("a frame")
}

#[test]
fn a_mask_at_full_coverage_changes_nothing_at_all() {
    // 255/255 is exactly one, so an unmasked pixel has to arrive unchanged
    // rather than nearly unchanged. A rounding that drifted here would show up
    // as a wipe's untouched side shifting by a code value.
    let frame = flat(4, 2, [200, 100, 50, 255]);
    let masked = media_editor_render::composite::masked(&frame, &[255; 8]).expect("a masked frame");
    assert_eq!(masked, frame);
}

#[test]
fn a_mask_at_no_coverage_leaves_nothing() {
    let frame = flat(2, 2, [200, 100, 50, 255]);
    let masked = media_editor_render::composite::masked(&frame, &[0; 4]).expect("a masked frame");
    assert_eq!(masked.to_packed().expect("samples"), vec![0; 16]);
}

#[test]
fn a_mask_scales_the_coverage_with_the_colour() {
    // Premultiplied, so halving the coverage halves the colour too. A frame
    // whose colour was scaled and whose alpha was not would claim more colour
    // than its coverage allows, and `over` refuses exactly that.
    //
    // But the two are halved in different *spaces*, and that is the whole of
    // what this test pins. A premultiplied sample is `encode(light x
    // coverage)`, so halving it means halving the **light**; coverage is a
    // fraction of a pixel's area and is linear in its stored value, so halving
    // that means halving the byte.
    let frame = flat(1, 1, [200, 100, 50, 255]);
    let masked = media_editor_render::composite::masked(&frame, &[128]).expect("a masked frame");
    // Worked out by hand, one channel at a time, at a coverage of 128/255 =
    // 0.50196:
    //
    //   red   200 decodes to 0.57751; x 0.50196 = 0.28993; encodes to 147
    //   green 100 decodes to 0.12744; x 0.50196 = 0.06397; encodes to  72
    //   blue   50 decodes to 0.03190; x 0.50196 = 0.01601; encodes to  34
    //   alpha 255 x 128 / 255 = 128, exactly
    //
    // The expected values scale linear light before encoding.
    assert_eq!(masked.to_packed().expect("samples"), vec![147, 72, 34, 128]);
    assert!(checked_premultiplied(&masked).is_ok());
}

#[test]
fn a_coverage_plane_of_the_wrong_size_is_refused() {
    let frame = flat(4, 2, [10, 10, 10, 255]);
    assert_eq!(
        media_editor_render::composite::masked(&frame, &[255; 7]),
        Err(RenderStatus::CoverageSizeMismatch)
    );
    assert_eq!(
        media_editor_render::composite::masked(&frame, &[255; 9]),
        Err(RenderStatus::CoverageSizeMismatch)
    );
}

#[test]
fn a_wipe_needs_no_operator_of_its_own() {
    // The whole claim of the shape work: mask the incoming layer with a
    // coverage plane and put it over the outgoing one. On the covered side the
    // result is entirely the incoming layer, on the uncovered side entirely
    // the outgoing one, and the pixel the edge passes through is the mix.
    use media_editor_core::Rational;
    use media_editor_render::shape::{Edge, Shape, plane};

    // Over a mid-grey rather than over black. Over black the bottom layer
    // contributes no light at all, so the result is just the masked top layer
    // encoded again -- and the linear-light answer and the code-value answer
    // agree exactly, which is a test that cannot tell them apart. That mistake
    // is already in this project's verification notes once; this is the second
    // place it would have been made.
    let incoming = flat(4, 1, [255, 255, 255, 255]);
    let outgoing = flat(4, 1, [128, 128, 128, 255]);
    let edge = Edge::new(
        Rational::ONE,
        Rational::ZERO,
        Rational::new(5, 2).expect("a rational"),
    )
    .expect("an edge");
    let coverage = plane(&Shape::half_plane(edge).expect("a shape"), 4, 1).expect("a plane");
    assert_eq!(coverage, vec![255, 255, 128, 0]);

    let wiped = over(
        &media_editor_render::composite::masked(&incoming, &coverage).expect("a masked frame"),
        &outgoing,
    )
    .expect("a wipe");
    let samples = wiped.to_packed().expect("samples");
    assert_eq!(&samples[0..4], &[255, 255, 255, 255], "wholly the incoming");
    assert_eq!(
        &samples[12..16],
        &[128, 128, 128, 255],
        "wholly the outgoing"
    );
    assert_eq!(
        samples[15], 255,
        "the programme stays opaque across the edge"
    );
    assert_eq!(samples[11], 255);
    // The edge pixel, worked out by hand. The incoming is white, so its light
    // is 1; masked to a coverage of 128/255 = 0.50196 it becomes light
    // 0.50196 at coverage 128. The grey underneath is stored 128, which is
    // 0.21586 of full light, and 128/255 of coverage leaves 0.49804 of it. So
    // the sum is 0.50196 + 0.21586 x 0.49804 = 0.60947, which encodes to 205.
    //
    // Mixing the code values instead gives 255 x 0.50196 + 128 x 0.49804 =
    // 192. Thirteen code values apart, and the linear answer is the *brighter*
    // one here.
    //
    // Pin the calculated value rather than relying on a brighter/darker rule.
    assert_eq!(samples[8], 205);
    assert_eq!(samples[9], 205);
    assert_eq!(samples[10], 205);
}
