// SPDX-License-Identifier: GPL-3.0-only
//! Typed render tasks with content-addressed identities.
//!
//! Nodes may refer only to earlier nodes, which prevents cycles. Each identity
//! includes the node kind, parameters, and input identities (R-8.5). Evaluation
//! order does not affect the result (R-6.2).

use alloc::vec::Vec;

use sapstudio_core::{Digest, Fixed, Rational, Sha256};
use sapstudio_media::{
    AlphaState, CacheKey, ColourDescription, Frame, FrameDescription, FramePool, TestPattern,
};

use crate::composite;
use crate::convert;
use crate::status::{RenderStatus, Result};

/// How many nodes one graph may hold.
///
/// A policy bound. A render graph for a frame of a timeline is tens of nodes;
/// one that reaches this has been generated by a loop that meant to stop.
pub const MAX_NODES: usize = 4096;

/// A reference to a node in a graph.
///
/// It is an index, and it is only ever handed out by [`Graph::add`] for a node
/// that already exists, which is what makes forward references — and therefore
/// cycles — impossible to write.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct NodeId(usize);

impl NodeId {
    /// Where in the graph this node sits.
    #[must_use]
    pub const fn index(self) -> usize {
        self.0
    }

    /// Build an identifier from an index, for tests that need to name a node
    /// that does not exist.
    ///
    /// Deliberately awkward to reach for: every identifier a caller should
    /// have comes from [`Graph::add`], and one built here is exactly the thing
    /// the graph is supposed to refuse.
    #[must_use]
    pub const fn from_index_for_test(index: usize) -> Self {
        Self(index)
    }
}

/// One step of a render.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Node {
    /// A frame drawn from nothing, which is what a generator is.
    Pattern {
        /// What to draw.
        pattern: TestPattern,
        /// What the result is.
        description: FrameDescription,
    },
    /// A frame of a single value.
    Blank {
        /// What the result is.
        description: FrameDescription,
    },
    /// A frame of media, named by what that media *is*.
    ///
    /// By content digest rather than by any project's identifier for it,
    /// because that is what makes a cached frame usable: the same footage in
    /// two projects is the same footage, and a node that named it by a
    /// project-local index would cache it twice and could never tell that the
    /// file had been swapped underneath.
    ///
    /// Where the frame comes from is a [`Library`], because a graph knows how to
    /// combine frames and nothing about where they live.
    Source {
        /// Which media.
        media: Digest,
        /// Which tick of it.
        tick: i64,
        /// What the result is.
        description: FrameDescription,
    },
    /// A frame at a fraction of its opacity.
    ///
    /// Every channel, coverage included: in premultiplied form the colour has
    /// already been multiplied by the coverage, so halving one means halving
    /// the other. Anything else leaves a frame claiming more colour than its
    /// coverage allows, which [`crate::over`] refuses and is right to.
    Fade {
        /// What to fade.
        input: NodeId,
        /// How much of it is showing.
        opacity: Rational,
    },
    /// A frame moved: scaled, shifted, or turned.
    ///
    /// The linear part is dimensionless and the offset is in fractions of the
    /// frame, so the node is the same node at every size — which is what lets
    /// a proxy render and a finish render share a cache key for everything
    /// above it. The map acts about the frame's **centre**, because scaling
    /// about the corner sends a picture sliding off to the lower right the
    /// moment somebody drags a scale slider.
    Transform {
        /// What to move.
        input: NodeId,
        /// The linear part, row-major and dimensionless.
        linear: [Rational; 4],
        /// The move, in fractions of the frame.
        offset: (Rational, Rational),
        /// The point the linear part acts about, in fractions of the frame.
        ///
        /// A field here rather than folded into `offset` by the caller,
        /// because the two are only interchangeable in *pixels*: the vector
        /// from the centre to the anchor scales per axis, and a linear part
        /// that mixes the axes — which is to say any rotation — does not
        /// commute with that scaling. See [`crate::resample::Mapping::about`].
        anchor: (Rational, Rational),
        /// Whether to weigh by area or between four samples.
        bilinear: bool,
    },
    /// A frame with everything outside a shape taken away.
    ///
    /// The corners are fractions of the frame, so the node is the same node at
    /// every size — which is what lets a proxy render and a finish render
    /// share a cache key for everything above the mask.
    Mask {
        /// What to mask.
        input: NodeId,
        /// The shape, in fractions of the frame.
        corners: alloc::vec::Vec<(Rational, Rational)>,
        /// Whether what is kept is what lies outside it.
        inverted: bool,
    },
    /// A picture made of words, at a size and a place somebody chose.
    ///
    /// A **source**, not a filter: a title is media the program generates, so
    /// this sits where a [`Node::Source`] would and everything above it — the
    /// grade, the mask, the transform, the fade — is the same machinery a
    /// recording goes through. That is the whole reason a title is media
    /// rather than a kind of item.
    ///
    /// Transparent everywhere the letters are not. The ink is three fractions
    /// of **full light** rather than three code values, for the reason the
    /// model gives: a code value is a number in an encoding, and the same
    /// number is a different colour in sRGB than in a linear working space.
    /// Naming it in light means the conversion happens once, here, through the
    /// table this frame's own description spells its colours with — so a
    /// limited-range title writes 235 for white and not the illegal 255 a
    /// hard-coded byte would.
    ///
    /// Distinct from [`Node::Legend`], which carries the words and *nothing
    /// else* because a slate's caption is not something anybody chose the look
    /// of. Here somebody did.
    Type {
        /// What to draw it as.
        description: FrameDescription,
        /// What it says, a line at a time.
        lines: alloc::vec::Vec<alloc::string::String>,
        /// The em, as a fraction of the frame's height.
        size: Rational,
        /// Where the middle of the block sits across the frame.
        across: Rational,
        /// And down it.
        down: Rational,
        /// How the lines sit against one another.
        alignment: crate::font::Alignment,
        /// What colour the letters are, as fractions of full light.
        ink: [Rational; 3],
    },
    /// A frame with a line of type set across it.
    ///
    /// A caption on a slate, not a title tool. It carries the words and
    /// nothing else — no size, no place, no colour — because everything a
    /// caption's *look* could be is a decision that would have to be the same
    /// on every slate to be worth anything, and a parameter nobody varies is a
    /// parameter that goes wrong in one place and nowhere else. Titles as
    /// something a project contains are a different feature with a different
    /// node.
    ///
    /// The words are in the identity, so two slates saying different things
    /// are two cache entries, and the same slate twice is one.
    ///
    /// It draws **nothing** on a frame too small to read it. That is not a
    /// failure and not a refusal: a slate whose caption is a grey smear has
    /// told the viewer something false about how much it knows, and the
    /// stripes underneath already say the one thing that matters.
    Legend {
        /// What to write on.
        input: NodeId,
        /// What it says.
        text: alloc::string::String,
        /// What it says instead when there is no room to read the first.
        ///
        /// Two strings rather than one, because a caption on a proxy has a
        /// real choice to make and neither answer is right at both sizes.
        /// "MEDIA OFFLINE 4F3C9A21" needs a frame three hundred pixels across
        /// to be read; the eight characters that *identify* the clip need a
        /// hundred and sixty. Setting the long one small enough to fit is a
        /// grey smear, and dropping straight to nothing throws away the part
        /// somebody actually needs.
        ///
        /// So: the whole sentence, then the part that matters, then nothing.
        brief: alloc::string::String,
    },
    /// A frame revealed behind a wipe's edge.
    ///
    /// [`Node::Fade`] with a different opacity at every pixel, which is what a
    /// wipe is. The edge's *position* is carried rather than the coverage
    /// plane it produces: four rationals hash into a node's identity and a
    /// plane of a million bytes would too, at a million times the cost, for a
    /// value that is a pure function of them and the frame's own size.
    Wipe {
        /// What to reveal.
        input: NodeId,
        /// How much of the direction runs across the picture.
        across: Rational,
        /// How much of it runs down.
        down: Rational,
        /// How far along its travel the edge is.
        fraction: Rational,
        /// How much of that travel the edge fades over.
        softness: Rational,
    },
    /// A frame with its coverage associated the other way.
    ///
    /// Premultiplying or dividing back out, named as its own step because
    /// [`Node::Convert`] refuses to do it: gaining, losing and re-associating
    /// alpha are three operations with three names, and a colour conversion
    /// that quietly performed one is the reason a keyed title arrives opaque.
    ///
    /// It exists because a look and a composite want opposite things. `over`
    /// is only correct on premultiplied samples; a lookup table is a
    /// non-linear function and on premultiplied samples computes `f(ac)` where
    /// `a·f(c)` was wanted. So a graded layer is fetched straight, graded, and
    /// associated here — which loses nothing, because the frame was never
    /// premultiplied to begin with.
    Associate {
        /// What to re-associate.
        input: NodeId,
        /// What the result is, which differs from the input only in how its
        /// coverage is carried.
        target: FrameDescription,
    },
    /// A frame with a look applied, some of the way on.
    ///
    /// The look is named by its digest rather than carried, because a cube is
    /// 35,937 triples and a graph is rebuilt for every instant. That also
    /// makes the node's identity depend on what the look *is*: a grade edited
    /// between two renders is a different key rather than a stale hit.
    ///
    /// The strength is a field rather than a second node in front of this one
    /// because it is not a second picture: it says where along the table's own
    /// output this frame lands, which is a thing only the table can compute.
    /// It is in the identity for the reason everything else here is — a look
    /// coming on over a shot is a different picture every frame, and a key
    /// that ignored the strength would serve the whole arrival out of one
    /// cache entry.
    Look {
        /// What to grade.
        input: NodeId,
        /// Which look.
        look: Digest,
        /// How far from ungraded to graded, from none of it to all of it.
        strength: Rational,
    },
    /// One frame over another.
    ///
    /// The two are stored in one array rather than as two named fields so that
    /// [`Node::inputs`] can hand back a slice of *both*. A version that
    /// returned only one of them would let a cycle through the other slip past
    /// the check that makes cycles unrepresentable — the whole point of that
    /// check being that it needs nobody to remember it.
    Over {
        /// What is underneath, then what goes on top.
        layers: [NodeId; 2],
    },
    /// A frame in another description.
    Convert {
        /// Where the picture comes from.
        input: NodeId,
        /// What the result is.
        target: FrameDescription,
    },
}

impl Node {
    /// What this node produces, without producing it — where it can say.
    ///
    /// A fade and an `over` produce whatever their inputs are described as, so
    /// they cannot answer on their own. [`Graph::description`] can, because it
    /// can follow the edge.
    #[must_use]
    pub const fn description(&self) -> Option<FrameDescription> {
        match self {
            Self::Pattern { description, .. }
            | Self::Blank { description }
            | Self::Type { description, .. }
            | Self::Source { description, .. } => Some(*description),
            Self::Convert { target, .. } | Self::Associate { target, .. } => Some(*target),
            Self::Fade { .. }
            | Self::Wipe { .. }
            | Self::Transform { .. }
            | Self::Mask { .. }
            | Self::Over { .. }
            | Self::Legend { .. }
            | Self::Look { .. } => None,
        }
    }

    /// The nodes this one reads.
    #[must_use]
    pub fn inputs(&self) -> &[NodeId] {
        match self {
            Self::Pattern { .. } | Self::Blank { .. } | Self::Source { .. } | Self::Type { .. } => {
                &[]
            }
            Self::Convert { input, .. }
            | Self::Fade { input, .. }
            | Self::Wipe { input, .. }
            | Self::Mask { input, .. }
            | Self::Legend { input, .. }
            | Self::Transform { input, .. }
            | Self::Look { input, .. }
            | Self::Associate { input, .. } => core::slice::from_ref(input),
            Self::Over { layers } => layers.as_slice(),
        }
    }
}

/// Where the things a graph names by digest come from.
///
/// A graph knows how to combine frames and nothing about where anything lives.
/// Decoding, reading, waiting and caching a file's own structure all sit behind
/// this, and none of it is the graph's business.
///
/// Two methods, because there are two kinds of heavy thing a graph refers to
/// without holding: frames of media, and lookup tables. Both are named by
/// content digest rather than by a handle, so the same footage or the same
/// grade in two projects is one cached thing, and a file swapped underneath is
/// a different key rather than a stale hit.
pub trait Library {
    /// The frame at `tick` of the media with this content digest.
    ///
    /// # Errors
    ///
    /// Whatever the source cannot do.
    fn frame(&mut self, media: Digest, tick: i64, description: FrameDescription) -> Result<Frame>;

    /// Whether the media is available while planning the graph.
    ///
    /// The default attempts the read. Implementations may return `false` to
    /// avoid caching fallback output under the source-media identity.
    fn available(&mut self, media: Digest) -> bool {
        let _ = media;
        true
    }

    /// Load the look identified by `look`.
    ///
    /// # Errors
    ///
    /// Whatever the library cannot do.
    fn look(&mut self, look: Digest) -> Result<crate::look::Look>;
}

/// A graph of render steps.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Graph {
    nodes: Vec<Node>,
    identities: Vec<Digest>,
}

impl Graph {
    /// An empty graph.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            nodes: Vec::new(),
            identities: Vec::new(),
        }
    }

    /// How many nodes there are.
    #[must_use]
    pub fn len(&self) -> usize {
        self.nodes.len()
    }

    /// Whether the graph holds nothing.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.nodes.is_empty()
    }

    /// One node.
    ///
    /// # Errors
    ///
    /// [`RenderStatus::UnknownNode`] if the identifier names nothing.
    pub fn node(&self, id: NodeId) -> Result<&Node> {
        self.nodes.get(id.0).ok_or(RenderStatus::UnknownNode)
    }

    /// Add a node, and return the identifier that names it.
    ///
    /// # Errors
    ///
    /// [`RenderStatus::UnknownNode`] if an input does not refer to an earlier
    /// node.
    /// [`RenderStatus::GraphTooLarge`] past the policy bound.
    pub fn add(&mut self, node: Node) -> Result<NodeId> {
        for input in node.inputs() {
            if input.0 >= self.nodes.len() {
                return Err(RenderStatus::UnknownNode);
            }
        }
        if self.nodes.len() >= MAX_NODES {
            return Err(RenderStatus::GraphTooLarge);
        }
        let identity = self.identity_of(&node)?;
        self.nodes
            .try_reserve(1)
            .map_err(|_| RenderStatus::OutOfMemory)?;
        self.identities
            .try_reserve(1)
            .map_err(|_| RenderStatus::OutOfMemory)?;
        let id = NodeId(self.nodes.len());
        self.nodes.push(node);
        self.identities.push(identity);
        Ok(id)
    }

    /// What a node is, as a digest over its kind, its parameters and the
    /// identities of everything it reads.
    ///
    /// # Errors
    ///
    /// [`RenderStatus::UnknownNode`].
    pub fn identity(&self, id: NodeId) -> Result<Digest> {
        self.identities
            .get(id.0)
            .copied()
            .ok_or(RenderStatus::UnknownNode)
    }

    /// The cache key a node's result is stored under.
    ///
    /// # Errors
    ///
    /// [`RenderStatus::UnknownNode`].
    pub fn cache_key(&self, id: NodeId) -> Result<CacheKey> {
        Ok(CacheKey::current(&[self.identity(id)?], b"render-graph"))
    }

    /// Compute a node's identity from its parts.
    fn identity_of(&self, node: &Node) -> Result<Digest> {
        let mut hasher = Sha256::new();
        hasher.update(b"sapstudio-render-node-v1");
        if !absorb_source(&mut hasher, node)? {
            self.absorb_filter(&mut hasher, node)?;
        }
        Ok(hasher.finish())
    }

    /// Absorb a node that reads other nodes.
    ///
    /// Split from [`Graph::identity_of`] along the line the graph is actually
    /// made of: a **source** is named by what it produces and nothing else,
    /// and a **filter** is named by its inputs' identities and its own
    /// parameters. Every filter arm below begins with the same two lines
    /// because of that, and every source arm cannot.
    fn absorb_filter(&self, hasher: &mut Sha256, node: &Node) -> Result<()> {
        match node {
            Node::Convert { input, target } => {
                hasher.update(&[3]);
                hasher.update(self.identity(*input)?.bytes());
                absorb_description(hasher, *target);
            }
            Node::Fade { input, opacity } => {
                hasher.update(&[5]);
                hasher.update(self.identity(*input)?.bytes());
                absorb_rationals(hasher, [*opacity]);
            }
            Node::Wipe {
                input,
                across,
                down,
                fraction,
                softness,
            } => {
                hasher.update(&[9]);
                hasher.update(self.identity(*input)?.bytes());
                absorb_rationals(hasher, [*across, *down, *fraction, *softness]);
            }
            Node::Transform {
                input,
                linear,
                offset,
                anchor,
                bilinear,
            } => {
                hasher.update(&[11]);
                hasher.update(self.identity(*input)?.bytes());
                hasher.update(&[u8::from(*bilinear)]);
                absorb_rationals(
                    hasher,
                    linear
                        .iter()
                        .copied()
                        .chain([offset.0, offset.1, anchor.0, anchor.1]),
                );
            }
            Node::Mask {
                input,
                corners,
                inverted,
            } => {
                hasher.update(&[10]);
                hasher.update(self.identity(*input)?.bytes());
                hasher.update(&[u8::from(*inverted)]);
                absorb_rationals(
                    hasher,
                    corners.iter().flat_map(|corner| [corner.0, corner.1]),
                );
            }
            Node::Associate { input, target } => {
                hasher.update(&[8]);
                hasher.update(self.identity(*input)?.bytes());
                absorb_description(hasher, *target);
            }
            Node::Look {
                input,
                look,
                strength,
            } => {
                hasher.update(&[7]);
                hasher.update(self.identity(*input)?.bytes());
                hasher.update(look.bytes());
                absorb_rationals(hasher, [*strength]);
            }
            Node::Legend { input, text, brief } => {
                hasher.update(&[12]);
                hasher.update(self.identity(*input)?.bytes());
                absorb_text(hasher, text, brief)?;
            }
            Node::Over { layers } => {
                hasher.update(&[6]);
                for layer in layers {
                    hasher.update(self.identity(*layer)?.bytes());
                }
            }
            Node::Pattern { .. } | Node::Blank { .. } | Node::Source { .. } | Node::Type { .. } => {
                unreachable();
            }
        }
        Ok(())
    }

    /// What a node produces, following the edges where the node cannot say.
    ///
    /// # Errors
    ///
    /// [`RenderStatus::UnknownNode`].
    pub fn description(&self, id: NodeId) -> Result<FrameDescription> {
        let node = self.node(id)?.clone();
        let Some(description) = node.description() else {
            // A fade and an `over` produce whatever their inputs are described
            // as, so follow the first edge. Every input of those two carries
            // the same description — `over` refuses two that differ — so the
            // first one answers for all of them.
            let input = *node.inputs().first().ok_or(RenderStatus::UnknownNode)?;
            return self.description(input);
        };
        Ok(description)
    }

    /// Evaluate one node, using and filling a pool.
    ///
    /// Evaluation is bottom-up over the node's own inputs, which are all
    /// earlier in the graph, so no recursion can run away and no visited set
    /// is needed.
    ///
    /// The pool is what makes this worth building a graph for rather than
    /// calling the operations directly: a node's key is a digest over its
    /// kind, its parameters and its inputs' identities, so a frame that two
    /// parts of a render both need is fetched and computed once. That matters
    /// most for [`Node::Source`], where the cost is a decode.
    ///
    /// # Errors
    ///
    /// [`RenderStatus::UnknownNode`], or any refusal from the work itself.
    pub fn evaluate(
        &self,
        id: NodeId,
        pool: &mut FramePool,
        library: &mut dyn Library,
    ) -> Result<Frame> {
        if let Some(frame) = pool.get(self.cache_key(id)?) {
            return Ok(frame.clone());
        }
        let node = self.node(id)?.clone();
        let frame = match node {
            Node::Pattern {
                pattern,
                description,
            } => pattern.render(description).map_err(RenderStatus::Media)?,
            Node::Blank { description } => {
                Frame::blank(description).map_err(RenderStatus::Media)?
            }
            Node::Convert { input, target } => {
                let source = self.evaluate(input, pool, library)?;
                convert::convert(&source, target)?
            }
            Node::Source {
                media: which,
                tick,
                description,
            } => {
                let frame = library.frame(which, tick, description)?;
                if *frame.description() != description {
                    // A source that answers with something other than what it
                    // was asked for has answered a different question, and
                    // converting it here would be a decision made in the wrong
                    // place — `Convert` is a node, with a name (R-1.3).
                    return Err(RenderStatus::SourceDescriptionMismatch);
                }
                frame
            }
            Node::Fade { input, opacity } => {
                let source = self.evaluate(input, pool, library)?;
                composite::faded(&source, opacity)?
            }
            Node::Wipe {
                input,
                across,
                down,
                fraction,
                softness,
            } => {
                let source = self.evaluate(input, pool, library)?;
                let (width, height) = extent(&source)?;
                let coverage =
                    crate::shape::feathered(across, down, fraction, softness, width, height)?;
                composite::masked(&source, &coverage)?
            }
            Node::Transform {
                input,
                linear,
                offset,
                anchor,
                bilinear,
            } => {
                let source = self.evaluate(input, pool, library)?;
                moved(&source, linear, offset, anchor, bilinear)?
            }
            Node::Mask {
                input,
                corners,
                inverted,
            } => {
                let source = self.evaluate(input, pool, library)?;
                let (width, height) = extent(&source)?;
                let coverage = crate::shape::masking(&corners, inverted, width, height)?;
                composite::masked(&source, &coverage)?
            }
            Node::Type {
                description,
                lines,
                size,
                across,
                down,
                alignment,
                ink,
            } => typeset(description, &lines, size, across, down, alignment, ink)?,
            Node::Legend { input, text, brief } => {
                let source = self.evaluate(input, pool, library)?;
                lettered(&source, &text, &brief)?
            }
            Node::Associate { input, target } => {
                associated(&self.evaluate(input, pool, library)?, target)?
            }
            Node::Look {
                input,
                look,
                strength,
            } => {
                let source = self.evaluate(input, pool, library)?;
                library.look(look)?.apply(&source, strength)?
            }
            Node::Over { layers } => {
                let bottom = self.evaluate(layers[0], pool, library)?;
                let top = self.evaluate(layers[1], pool, library)?;
                composite::over(&top, &bottom)?
            }
        };
        // A frame too large for the pool is still a correct result; it simply
        // is not kept. Refusing the render because the cache is small would be
        // the cache making a decision that is not its to make.
        match pool.insert(self.cache_key(id)?, frame.clone()) {
            Ok(()) | Err(sapstudio_media::MediaStatus::FrameLargerThanPool) => Ok(frame),
            Err(status) => Err(RenderStatus::Media(status)),
        }
    }
}

/// A frame with its coverage associated the other way.
///
/// Anything but the two real directions is refused: a frame with no coverage
/// has nothing to associate, and a node asking for the state its input is
/// already in is claiming to change something it is not changing.
fn associated(source: &Frame, target: FrameDescription) -> Result<Frame> {
    match (source.description().alpha(), target.alpha()) {
        (Some(AlphaState::Straight), Some(AlphaState::Premultiplied)) => {
            composite::premultiply(source)
        }
        (Some(AlphaState::Premultiplied), Some(AlphaState::Straight)) => {
            composite::unpremultiply(source)
        }
        _ => Err(RenderStatus::WrongAlphaState),
    }
}

/// A frame of coloured type on nothing.
///
/// Premultiplied by the same conversion every other layer goes through, for
/// the reason [`lettered`] gives: a premultiplied sample is the colour times
/// the coverage *in light*, and code values are not light.
///
/// The ink arrives as three fractions of full light and leaves as three code
/// values, and the table that converts it is built from *this frame's* colour
/// description. That is the whole argument for naming a colour in light: the
/// same ink is 255 in a full-range frame and 235 in a limited-range one, and
/// neither number had to be written down anywhere.
fn typeset(
    description: FrameDescription,
    lines: &[alloc::string::String],
    size: Rational,
    across: Rational,
    down: Rational,
    alignment: crate::font::Alignment,
    ink: [Rational; 3],
) -> Result<Frame> {
    let geometry = description.geometry();
    let width = usize::try_from(geometry.width()).map_err(|_| RenderStatus::OutsideDomain)?;
    let height = usize::try_from(geometry.height()).map_err(|_| RenderStatus::OutsideDomain)?;
    let borrowed: alloc::vec::Vec<&str> = lines.iter().map(alloc::string::String::as_str).collect();
    let coverage = crate::font::title(&borrowed, size, across, down, alignment, width, height)?
        .plane(width, height)?;
    let straight = description
        .with_alpha(AlphaState::Straight)
        .map_err(RenderStatus::Media)?;
    let mut packed = alloc::vec::Vec::new();
    packed
        .try_reserve(
            coverage
                .len()
                .checked_mul(4)
                .ok_or(RenderStatus::OutOfMemory)?,
        )
        .map_err(|_| RenderStatus::OutOfMemory)?;
    let table = crate::convert::TransferTable::build(straight.colour())?;
    let mut colour = [0_u8; 3];
    for (slot, channel) in colour.iter_mut().zip(ink) {
        *slot = table.encode(Fixed::from_rational(channel)?);
    }
    for alpha in &coverage {
        packed.extend_from_slice(&[colour[0], colour[1], colour[2], *alpha]);
    }
    let letters = Frame::from_packed(straight, &packed).map_err(RenderStatus::Media)?;
    let associated = composite::premultiply(&letters)?;
    if description.alpha() == Some(AlphaState::Premultiplied) {
        Ok(associated)
    } else {
        // A description that asks for straight coverage gets it, rather than a
        // frame labelled one way and holding the other.
        composite::unpremultiply(&associated)
    }
}

/// A frame resampled through a transform about its own centre.
fn moved(
    source: &Frame,
    linear: [Rational; 4],
    offset: (Rational, Rational),
    anchor: (Rational, Rational),
    bilinear: bool,
) -> Result<Frame> {
    let described = *source.description();
    let geometry = described.geometry();
    let mapping = crate::resample::Mapping::about(
        linear,
        offset,
        anchor,
        geometry.width(),
        geometry.height(),
    )?;
    crate::resample::resample(
        source,
        described,
        mapping,
        if bilinear {
            crate::resample::Filter::Bilinear
        } else {
            crate::resample::Filter::Area
        },
    )
}

/// A frame with a caption set across it, or the frame unchanged.
///
/// White type, centred, on a baseline two thirds of the way down, at whatever
/// size lets the run fit the width with a margin — capped so a short caption
/// on a wide frame does not become a billboard.
///
/// The type is built **straight** and premultiplied by the same conversion
/// every other layer goes through, rather than by writing the coverage into
/// all four channels. Those two are not the same thing: a premultiplied sample
/// is the colour times the coverage *in light*, and code values are not light.
/// Writing the coverage byte into the colour would draw type that is too dark
/// at every edge, everywhere, by exactly the amount the transfer curve bends —
/// which is the same mistake the compositor was built to stop making.
fn lettered(source: &Frame, text: &str, brief: &str) -> Result<Frame> {
    let (width, height) = extent(source)?;
    let mut chosen = crate::font::caption(text, width, height)?;
    if chosen.is_none() {
        chosen = crate::font::caption(brief, width, height)?;
    }
    let Some(run) = chosen else {
        // Too small even for the short one. The stripes underneath already say
        // the one thing that matters, and a grey smear would say it less well.
        return Ok(source.clone());
    };
    let coverage = run.plane(width, height)?;
    let described = source.description();
    let straight = described
        .with_alpha(AlphaState::Straight)
        .map_err(RenderStatus::Media)?;
    let mut packed = alloc::vec::Vec::new();
    packed
        .try_reserve(
            coverage
                .len()
                .checked_mul(4)
                .ok_or(RenderStatus::OutOfMemory)?,
        )
        .map_err(|_| RenderStatus::OutOfMemory)?;
    // Full light, spelled the way this frame spells it. A hard-coded 255 is
    // an *illegal* code value in limited range, which some equipment reads as
    // a sync pattern -- so even a caption nobody chose the colour of has to
    // ask the table what white is.
    let white = crate::convert::TransferTable::build(straight.colour())?.encode(Fixed::ONE);
    for alpha in &coverage {
        packed.extend_from_slice(&[white, white, white, *alpha]);
    }
    let letters = Frame::from_packed(straight, &packed).map_err(RenderStatus::Media)?;
    composite::over(&composite::premultiply(&letters)?, source)
}

/// A frame's size, as the counts a rasteriser wants.
fn extent(frame: &Frame) -> Result<(usize, usize)> {
    let geometry = frame.description().geometry();
    Ok((
        usize::try_from(geometry.width()).map_err(|_| RenderStatus::OutsideDomain)?,
        usize::try_from(geometry.height()).map_err(|_| RenderStatus::OutsideDomain)?,
    ))
}

/// Absorb a node that reads nothing, saying whether it was one.
///
/// A source is named by what it produces: a pattern by which pattern, a title
/// by what it says. None of them has an input to fold in, which is exactly
/// what makes them sources.
fn absorb_source(hasher: &mut Sha256, node: &Node) -> Result<bool> {
    match node {
        Node::Pattern {
            pattern,
            description,
        } => {
            hasher.update(&[1]);
            absorb_pattern(hasher, *pattern);
            absorb_description(hasher, *description);
        }
        Node::Blank { description } => {
            hasher.update(&[2]);
            absorb_description(hasher, *description);
        }
        Node::Source {
            media,
            tick,
            description,
        } => {
            hasher.update(&[4]);
            hasher.update(media.bytes());
            hasher.update(&tick.to_le_bytes());
            absorb_description(hasher, *description);
        }
        Node::Type {
            description,
            lines,
            size,
            across,
            down,
            alignment,
            ink,
        } => {
            hasher.update(&[13]);
            absorb_description(hasher, *description);
            hasher.update(
                &u64::try_from(lines.len())
                    .map_err(|_| RenderStatus::OutsideDomain)?
                    .to_le_bytes(),
            );
            for line in lines {
                absorb_text(hasher, line, "")?;
            }
            hasher.update(&[match alignment {
                crate::font::Alignment::Left => 0,
                crate::font::Alignment::Centre => 1,
                crate::font::Alignment::Right => 2,
            }]);
            absorb_rationals(hasher, [*size, *across, *down]);
            absorb_rationals(hasher, *ink);
        }
        _ => return Ok(false),
    }
    Ok(true)
}

/// A match arm the shape of the type makes impossible.
///
/// Not a panic and not a refusal that could be mistaken for a real one: the
/// two halves of a node's identity partition the node kinds, and this is the
/// half of each partition the other one covers.
const fn unreachable() {}

/// Absorb exact numbers into a hash, each as its two halves.
///
/// Both halves rather than one scaled integer, for the reason the project file
/// writes them the same way: a third is a third, and a node keyed by a decimal
/// near it would be a node that two builds disagreed about.
fn absorb_rationals(hasher: &mut Sha256, values: impl IntoIterator<Item = Rational>) {
    for held in values {
        hasher.update(&held.numerator().to_le_bytes());
        hasher.update(&held.denominator().to_le_bytes());
    }
}

/// Absorb a legend's two captions into a hash, each length first.
///
/// The length before the bytes, so two captions cannot run together into one
/// digest: "AB" then "C" and "A" then "BC" are different slates and have to be
/// different keys.
fn absorb_text(hasher: &mut Sha256, text: &str, brief: &str) -> Result<()> {
    for held in [text, brief] {
        hasher.update(
            &u64::try_from(held.len())
                .map_err(|_| RenderStatus::OutsideDomain)?
                .to_le_bytes(),
        );
        hasher.update(held.as_bytes());
    }
    Ok(())
}

/// Absorb a pattern's identity into a hash.
fn absorb_pattern(hasher: &mut Sha256, pattern: TestPattern) {
    match pattern {
        TestPattern::Bars => hasher.update(&[1]),
        TestPattern::Ramp => hasher.update(&[2]),
        TestPattern::Checkerboard { square } => {
            hasher.update(&[3]);
            hasher.update(&square.to_le_bytes());
        }
        TestPattern::Flat { value } => {
            hasher.update(&[4, value]);
        }
        TestPattern::Offline => hasher.update(&[5]),
    }
}

/// Absorb a description's identity into a hash.
fn absorb_description(hasher: &mut Sha256, description: FrameDescription) {
    hasher.update(&description.geometry().width().to_le_bytes());
    hasher.update(&description.geometry().height().to_le_bytes());
    hasher.update(&description.pixel_aspect().numerator().to_le_bytes());
    hasher.update(&description.pixel_aspect().denominator().to_le_bytes());
    // The format and the colour go in through the frame's own tagging, which
    // already has stable numbers for them: a blank frame of this description
    // is a value whose digest covers exactly these things.
    match Frame::blank(description) {
        Ok(frame) => hasher.update(frame.digest().bytes()),
        Err(_) => hasher.update(b"undescribable"),
    }
}

/// The description a colour conversion of a node would produce, for callers
/// building a graph who want to check before they add.
#[must_use]
pub fn converted_description(
    source: FrameDescription,
    colour: ColourDescription,
) -> Option<FrameDescription> {
    FrameDescription::new(
        source.geometry(),
        source.format(),
        colour,
        source.siting(),
        source.alpha(),
        source.pixel_aspect(),
    )
    .ok()
}
