// SPDX-License-Identifier: GPL-3.0-only
//! An ordered, gap-free, overlap-free series of items.
//!
//! A track stores only its items, in order. An item's position is the sum of
//! the lengths before it, so two items *cannot* overlap and there *cannot* be
//! an unaccounted hole: neither is representable. Every editing operation is
//! therefore an operation on a list, and the invariant that costs other
//! editors a validation pass costs this one nothing.

use alloc::vec::Vec;

use media_editor_core::{Duration, Instant, Rational, TimeRange, Timebase};

use crate::bounded::insert_bounded;
use crate::curve::{Automation, Curve, Keyframe, KeyframeEdit};
use crate::item::Item;
use crate::status::{ModelStatus, Result};

/// How many items one track may hold. A policy bound, not an architectural
/// one: a feature-length cut is a few thousand edits per track, and a track
/// that reaches this has almost certainly been generated by a loop that meant
/// to stop.
pub const MAX_ITEMS_PER_TRACK: usize = 65_536;

/// What a track carries.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum TrackKind {
    /// Pictures.
    Video,
    /// Sound.
    Audio,
}

/// The quietest level a fader may be set to, in decibels.
///
/// This bound is the mixer's, restated here because the model may not depend
/// on the sound crate — the two are siblings. `the_two_fader_bounds_agree` in
/// the application's tests asserts that these are the same numbers, so the
/// duplication cannot drift without something failing.
pub const MINIMUM_DECIBELS: i64 = -120;

/// The loudest level a fader may be set to, in decibels.
pub const MAXIMUM_DECIBELS: i64 = 24;

/// Where a track's fader is set.
///
/// The decibel value is kept, not the factor it becomes. A decibel is what the
/// user set and what the interface shows; a factor is the result of a
/// logarithm, and storing that instead would mean a fader moved and moved back
/// no longer sits exactly where it started.
///
/// `None` is the off detent rather than a very small number, because the
/// logarithm of zero is not a value on this scale — the same distinction the
/// mixer makes, for the same reason.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Fader {
    decibels: Option<Rational>,
}

impl Fader {
    /// A fader at unity: the track, untouched.
    pub const UNITY: Self = Self {
        decibels: Some(Rational::ZERO),
    };

    /// A muted track.
    pub const MUTED: Self = Self { decibels: None };

    /// A fader at a level.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::FaderOutOfRange`] outside [`MINIMUM_DECIBELS`] to
    /// [`MAXIMUM_DECIBELS`].
    pub fn at(decibels: Rational) -> Result<Self> {
        let low = Rational::new(MINIMUM_DECIBELS, 1)?;
        let high = Rational::new(MAXIMUM_DECIBELS, 1)?;
        if decibels < low || decibels > high {
            return Err(ModelStatus::FaderOutOfRange);
        }
        Ok(Self {
            decibels: Some(decibels),
        })
    }

    /// Where it is set, or `None` if the track is muted.
    #[must_use]
    pub const fn decibels(self) -> Option<Rational> {
        self.decibels
    }

    /// Whether the track is off rather than quiet.
    #[must_use]
    pub const fn is_muted(self) -> bool {
        self.decibels.is_none()
    }
}

/// A dissolve at a cut.
///
/// A transition sits *at a boundary* rather than being an item of its own, and
/// that is the decision everything else here follows from. An item of its own
/// would have to overlap its neighbours, and this model's whole guarantee is
/// that a track's items tile it with no overlap and no missing region — a
/// guarantee that holds by construction, not by validation, and is not worth
/// giving up.
///
/// So a transition is a length and the cut it is centred on. During it, both
/// neighbouring clips are on screen at once: the outgoing one is reaching past
/// its out point into material it has but does not otherwise use, and the
/// incoming one is starting early into the same. That material is called
/// handles, and a clip either has it or the render finds out — the model does
/// not check, for the same reason it does not check a clip against its media's
/// length anywhere else.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Transition {
    boundary: usize,
    duration: Duration,
    kind: TransitionKind,
}

/// Which way a transition reveals the incoming clip.
///
/// The two are not variations on one thing. A dissolve mixes the whole frame
/// by a fraction that changes over time; a wipe shows all of one clip on one
/// side of a moving line and all of the other on the other. Rendering them is
/// different arithmetic — a fade against a coverage plane — so the model says
/// which rather than leaving a renderer to infer it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TransitionKind {
    /// A cross-fade of the whole frame.
    Dissolve,
    /// A line sweeping across the frame.
    Wipe(Wipe),
}

/// A linear wipe: a straight edge sweeping in a direction.
///
/// The direction is a **rational vector**, not an angle. An angle would need a
/// sine and a cosine, which are not exact, and every interface that offers an
/// angle can turn it into a vector at the moment somebody sets it — so the
/// approximation, if there is one, happens once at the edge of the system
/// rather than on every frame of every render.
///
/// It also makes the wipes anybody actually uses exact: straight across is
/// `(1, 0)`, straight down is `(0, 1)`, and a true diagonal is `(1, 1)` rather
/// than a rounding of forty-five degrees.
///
/// The vector points the way the covered region *grows*. Its length carries no
/// meaning — `(2, 0)` and `(1, 0)` are the same wipe — because the edge's
/// position is set by the transition's fraction rather than by how long the
/// vector is.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Wipe {
    across: Rational,
    down: Rational,
    softness: Rational,
}

impl Wipe {
    /// Straight across, left to right, with a hard edge.
    pub const RIGHTWARD: Self = Self {
        across: Rational::ONE,
        down: Rational::ZERO,
        softness: Rational::ZERO,
    };

    /// Straight down, top to bottom, with a hard edge.
    pub const DOWNWARD: Self = Self {
        across: Rational::ZERO,
        down: Rational::ONE,
        softness: Rational::ZERO,
    };

    /// A wipe in a direction, with a hard edge.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::DegenerateWipe`] if both components are zero, which
    /// names no direction and would leave the edge nowhere.
    pub fn new(across: Rational, down: Rational) -> Result<Self> {
        Self::soft(across, down, Rational::ZERO)
    }

    /// A wipe whose edge fades over a fraction of its travel.
    ///
    /// Softness is a **fraction of the wipe's travel** rather than a distance
    /// in pixels, so it means the same thing at every size and every angle,
    /// and a project conformed to a different frame size keeps the look
    /// somebody set rather than keeping a number of pixels that no longer
    /// corresponds to it.
    ///
    /// Nought is a hard edge and is exactly the hard edge — not a very narrow
    /// ramp that rounds to one.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::DegenerateWipe`] for no direction, and
    /// [`ModelStatus::SoftnessOutOfRange`] for a softness outside nought to
    /// one — past one the ramp would start before the wipe does.
    pub fn soft(across: Rational, down: Rational, softness: Rational) -> Result<Self> {
        if across.is_zero() && down.is_zero() {
            return Err(ModelStatus::DegenerateWipe);
        }
        if softness.numerator() < 0 || softness.checked_sub(Rational::ONE)?.is_positive() {
            return Err(ModelStatus::SoftnessOutOfRange);
        }
        Ok(Self {
            across,
            down,
            softness,
        })
    }

    /// How much of the travel the edge fades over.
    #[must_use]
    pub const fn softness(self) -> Rational {
        self.softness
    }

    /// How much of the direction runs across the picture.
    #[must_use]
    pub const fn across(self) -> Rational {
        self.across
    }

    /// How much of it runs down.
    #[must_use]
    pub const fn down(self) -> Rational {
        self.down
    }
}

impl Transition {
    /// A dissolve of `duration`, centred on the cut before item `boundary`.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::EmptyItem`] for a zero length, and
    /// [`ModelStatus::UnknownItem`] for boundary zero, which is the start of
    /// the track and not a cut between two things.
    pub fn new(boundary: usize, duration: Duration) -> Result<Self> {
        Self::of(boundary, duration, TransitionKind::Dissolve)
    }

    /// A wipe of `duration`, centred on the same cut.
    ///
    /// Centred for the same reason a dissolve is, and it is the same
    /// arithmetic: the fraction that decides how far a dissolve has faded
    /// decides how far a wipe's edge has travelled. Everything about *when*
    /// a transition happens is shared; only what it does to the picture
    /// differs.
    ///
    /// # Errors
    ///
    /// The same as [`Transition::new`].
    pub fn wiping(boundary: usize, duration: Duration, wipe: Wipe) -> Result<Self> {
        Self::of(boundary, duration, TransitionKind::Wipe(wipe))
    }

    /// A transition of a stated kind.
    ///
    /// # Errors
    ///
    /// The same as [`Transition::new`].
    pub fn of(boundary: usize, duration: Duration, kind: TransitionKind) -> Result<Self> {
        if duration.is_zero() {
            return Err(ModelStatus::EmptyItem);
        }
        if boundary == 0 {
            return Err(ModelStatus::UnknownItem);
        }
        Ok(Self {
            boundary,
            duration,
            kind,
        })
    }

    /// What this transition does to the picture.
    #[must_use]
    pub const fn kind(&self) -> TransitionKind {
        self.kind
    }

    /// Which cut this sits on: between items `boundary - 1` and `boundary`.
    #[must_use]
    pub const fn boundary(&self) -> usize {
        self.boundary
    }

    /// How long it lasts.
    #[must_use]
    pub const fn duration(&self) -> Duration {
        self.duration
    }
}

/// One lane of a sequence.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Track {
    kind: TrackKind,
    timebase: Timebase,
    items: Vec<Item>,
    fader: Fader,
    transitions: Vec<Transition>,
    opacity: Option<Curve>,
    level: Option<Curve>,
}

impl Track {
    /// An empty track.
    #[must_use]
    pub const fn new(kind: TrackKind, timebase: Timebase) -> Self {
        Self {
            kind,
            timebase,
            items: Vec::new(),
            fader: Fader::UNITY,
            transitions: Vec::new(),
            opacity: None,
            level: None,
        }
    }

    /// The dissolves on this track, in order of the cuts they sit on.
    #[must_use]
    pub fn transitions(&self) -> &[Transition] {
        &self.transitions
    }

    /// The dissolve at a cut, if there is one.
    #[must_use]
    pub fn transition_at(&self, boundary: usize) -> Option<Transition> {
        self.transitions
            .iter()
            .copied()
            .find(|held| held.boundary == boundary)
    }

    /// Add a dissolve at a cut.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::UnknownItem`] if the cut is not between two items,
    /// [`ModelStatus::NotAClip`] if either side is a gap — there is nothing to
    /// dissolve from or to — [`ModelStatus::TransitionExists`] if there is
    /// already one there, [`ModelStatus::TransitionTooLong`] if it outlasts
    /// either neighbour, and [`ModelStatus::CapacityExhausted`] or
    /// [`ModelStatus::OutOfMemory`].
    pub(crate) fn add_transition(&mut self, transition: Transition) -> Result<()> {
        let boundary = transition.boundary;
        if boundary == 0 || boundary >= self.items.len() {
            return Err(ModelStatus::UnknownItem);
        }
        if transition.duration.timebase() != self.timebase {
            return Err(media_editor_core::CoreStatus::TimebaseMismatch.into());
        }
        self.transition_fits(&transition, &[])?;
        if self.transition_at(boundary).is_some() {
            return Err(ModelStatus::TransitionExists);
        }
        let position = self
            .transitions
            .iter()
            .position(|held| held.boundary > boundary)
            .unwrap_or(self.transitions.len());
        insert_bounded(
            &mut self.transitions,
            position,
            transition,
            MAX_ITEMS_PER_TRACK,
        )
    }

    /// Whether the items around a transition can still carry it.
    ///
    /// Out of [`Track::add_transition`] because it is not only asked when one
    /// is added. A **roll** or a **slide** changes the very lengths and in
    /// points these two conditions are about, so either can turn a dissolve
    /// that fitted into one that does not — and a check that only ran at the
    /// moment somebody drew the dissolve would let a later trim leave the
    /// track describing a transition it cannot perform.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::NotAClip`], [`ModelStatus::TransitionTooLong`], and
    /// [`ModelStatus::SourceBeforeStart`].
    ///
    /// `proposed` names items that are about to change, so a trim can ask
    /// whether a dissolve survives it *before* writing anything.
    fn transition_fits(&self, transition: &Transition, proposed: &[(usize, Item)]) -> Result<()> {
        let boundary = transition.boundary;
        let at = |index: usize| -> &Item {
            proposed
                .iter()
                .find(|(held, _)| *held == index)
                .map_or(&self.items[index], |(_, item)| item)
        };
        for side in [boundary - 1, boundary] {
            if !matches!(at(side), Item::Clip(_)) {
                // A dissolve to black is a dissolve to a clip of black, not a
                // dissolve to nothing. Making a gap mean black here would be
                // deciding what the programme shows in a place that does not
                // decide that.
                return Err(ModelStatus::NotAClip);
            }
            if transition.duration.compare(at(side).duration())? == core::cmp::Ordering::Greater {
                // A dissolve longer than the clip it dissolves from would need
                // material from before that clip began, which is a different
                // edit.
                return Err(ModelStatus::TransitionTooLong);
            }
        }
        // The incoming clip has to start early, into material before its in
        // point. How much of that exists is a question about the media, which
        // this does not know — but whether the clip's in point is even far
        // enough into its source for there to be room is a question about the
        // clip, which it does. Half a dissolve of handle, rounded down, which
        // is where the dissolve begins relative to the cut.
        let opening = transition.duration.ticks() / 2;
        if let Item::Clip(incoming) = at(boundary)
            && incoming.source_start() < opening
        {
            return Err(ModelStatus::SourceBeforeStart);
        }
        Ok(())
    }

    /// Take a dissolve off a cut, returning it.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::UnknownTransition`] if there is none there.
    pub(crate) fn remove_transition(&mut self, boundary: usize) -> Result<Transition> {
        let position = self
            .transitions
            .iter()
            .position(|held| held.boundary == boundary)
            .ok_or(ModelStatus::UnknownTransition)?;
        Ok(self.transitions.remove(position))
    }

    /// Whether any dissolve sits at or after a boundary.
    ///
    /// An edit that inserts or removes an item renumbers every boundary after
    /// it, which would move a dissolve to a cut nobody put it on. Rather than
    /// renumber them — and have to renumber them back exactly on undo — such
    /// an edit is refused while a dissolve is in the way, and the dissolve is
    /// taken off first. That is one more step for the user and one less way
    /// for a project to end up describing something nobody edited (R-1.3).
    pub(crate) fn transition_from(&self, boundary: usize) -> bool {
        self.transitions
            .iter()
            .any(|held| held.boundary >= boundary)
    }

    /// Everything a split at `index` can refuse, and the room it will need.
    ///
    /// The first half of [`crate::Sequence`]'s column cut. `split` reserves
    /// before it mutates so that one track's cut is atomic; a *column* of cuts
    /// needs the reservation made on every track before any of them is
    /// written, which is what this is for.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::TransitionInTheWay`], [`ModelStatus::UnknownItem`],
    /// [`ModelStatus::CapacityExhausted`] or [`ModelStatus::OutOfMemory`].
    pub(crate) fn make_room_to_split(&mut self, index: usize) -> Result<()> {
        if self.transition_from(index + 1) {
            return Err(ModelStatus::TransitionInTheWay);
        }
        if index >= self.items.len() {
            return Err(ModelStatus::UnknownItem);
        }
        if self.items.len() >= MAX_ITEMS_PER_TRACK {
            return Err(ModelStatus::CapacityExhausted);
        }
        self.items
            .try_reserve(1)
            .map_err(|_| ModelStatus::OutOfMemory)
    }

    /// Write a split that [`Track::make_room_to_split`] has already cleared.
    ///
    /// Infallible, and that is the point rather than an observation: it is
    /// what lets a column of cuts be published all at once. Everything that
    /// could refuse has refused already, in a pass that touched nothing.
    pub(crate) fn place_split(&mut self, index: usize, head: Item, tail: Item) {
        if let Some(slot) = self.items.get_mut(index) {
            *slot = head;
            self.items.insert(index + 1, tail);
        }
    }

    /// Write a join whose result has already been computed.
    ///
    /// Infallible for the same reason, and easier: a track loses an item, so
    /// there is nothing to reserve.
    pub(crate) fn place_join(&mut self, boundary: usize, joined: Item) {
        if boundary == 0 || boundary >= self.items.len() {
            return;
        }
        if let Some(slot) = self.items.get_mut(boundary - 1) {
            *slot = joined;
            self.items.remove(boundary);
        }
    }

    /// Whether a transition sits on either boundary of an item.
    ///
    /// The two an item touches: the cut before it and the cut after it. A
    /// transition on either would be left mixing a gap if the item became one,
    /// which the layer stack refuses at the frame rather than at the edit.
    ///
    /// Deliberately narrower than [`Track::transition_from`], and the
    /// difference is what an edit does to the *numbering*. A split or a join
    /// inserts or removes an item, so every boundary after it moves and a
    /// transition beyond the edit would end up on a cut nobody put it on --
    /// hence "at or after". A lift replaces in place, so nothing is renumbered
    /// and only these two boundaries can be affected. The coarser check would
    /// refuse a lift at the head of a programme because somebody drew a
    /// dissolve at the end of it, which is a refusal with nothing behind it.
    ///
    /// It asks [`Track::transition_at`] rather than searching the list again,
    /// so there is one place that knows where a transition sits.
    pub(crate) fn transition_touching(&self, index: usize) -> bool {
        self.transition_at(index).is_some() || self.transition_at(index + 1).is_some()
    }

    /// The same question, for a caller outside this crate.
    ///
    /// [`crate::Sequence::cuttable_at`] and [`crate::Sequence::healable_at`]
    /// leave a track out when a dissolve is in the way, and they have to ask
    /// the *same* question `split` and `join` ask or the two drift: a set that
    /// named a track those refuse would turn a razor into a refusal at the
    /// moment somebody dragged it, which is the worst place to find out.
    #[must_use]
    pub fn has_transition_from(&self, boundary: usize) -> bool {
        self.transition_from(boundary)
    }

    /// Where this track's fader is set.
    #[must_use]
    pub const fn fader(&self) -> Fader {
        self.fader
    }

    /// Move the fader, returning where it was.
    pub(crate) const fn set_fader(&mut self, fader: Fader) -> Fader {
        let previous = self.fader;
        self.fader = fader;
        previous
    }

    /// How see-through this track is over time, if it has been animated.
    ///
    /// [`None`] is fully opaque and is not the same as a curve that happens to
    /// hold one: a track with no automation has none to read, and telling the
    /// two apart is what lets the automation be switched off and back on
    /// without losing the shape somebody drew.
    #[must_use]
    pub const fn opacity(&self) -> Option<&Curve> {
        self.opacity.as_ref()
    }

    /// How see-through this track is at one instant.
    ///
    /// One when there is no automation. Clamped into nought-to-one when there
    /// is, because a curve may overshoot on purpose and nothing can be more
    /// than fully opaque or less than fully clear.
    ///
    /// Clamping here is not the same decision as refusing an ease handle
    /// outside its span. A handle outside the span changes which curve was
    /// drawn, silently; a value past full opacity is the curve the editor drew
    /// meeting a physical limit, and saturating at it is what the limit means.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::WrongTimebase`] for an instant counted another way.
    pub fn opacity_at(&self, instant: Instant) -> Result<Rational> {
        let Some(curve) = &self.opacity else {
            return Ok(Rational::ONE);
        };
        let held = curve.value_at(instant)?;
        Ok(held.clamp(Rational::ZERO, Rational::ONE))
    }

    /// Animate this track's opacity, or stop animating it.
    ///
    /// Hands back what was there, for the same reason [`Track::set_fader`]
    /// does: an edit that had to read the old value first would be two
    /// operations, and a failure between them would leave the two disagreeing.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::OpacityOnSound`] for a sound track, whose level is its
    /// fader and not an opacity, and [`ModelStatus::WrongTimebase`] for a
    /// curve counted another way.
    pub(crate) fn set_opacity(&mut self, opacity: Option<Curve>) -> Result<Option<Curve>> {
        if let Some(curve) = &opacity {
            if self.kind != TrackKind::Video {
                return Err(ModelStatus::OpacityOnSound);
            }
            if curve.timebase() != self.timebase {
                return Err(ModelStatus::WrongTimebase);
            }
        }
        Ok(core::mem::replace(&mut self.opacity, opacity))
    }

    /// This track's fader position over time, if it is being driven.
    ///
    /// In decibels, the same units [`Fader`] is set in, so an automated fader
    /// and a static one are the same control. [`None`] is a fader that is not
    /// being driven — the static [`Track::fader`] holds instead — and it is
    /// not the same as a curve that happens to sit at that value: taking
    /// automation off must give back the fader, not a flat line at wherever
    /// the automation last was.
    #[must_use]
    pub const fn level(&self) -> Option<&Curve> {
        self.level.as_ref()
    }

    /// The gain this track is at, at one instant.
    ///
    /// The automation when there is any, the static fader when there is not.
    /// Automation *replaces* the fader rather than adding to it, which is what
    /// a console does: a fader being driven is a fader whose position is being
    /// set, not one being trimmed. Multiplying the two would make the number
    /// on the surface mean nothing on its own.
    ///
    /// Out of range is clamped rather than refused, because a curve may
    /// overshoot on purpose and the fader's travel is a physical end stop —
    /// the same distinction as a track opacity past full.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::WrongTimebase`] for an instant counted another way, and
    /// [`ModelStatus::Time`] on arithmetic that will not fit.
    pub fn fader_at(&self, instant: Instant) -> Result<Fader> {
        if self.fader.is_muted() {
            // Mute wins, and it is not a fader position — it is a switch. A
            // curve holds decibels and so cannot reach the off detent at all;
            // its floor is [`MINIMUM_DECIBELS`], which is very quiet and is
            // still a level. Letting automation speak for a muted track would
            // mean a track turned off at the surface coming back on because
            // somebody drew a fade on it, which is not what either control
            // says.
            return Ok(Fader::MUTED);
        }
        let Some(curve) = &self.level else {
            return Ok(self.fader);
        };
        let held = curve.value_at(instant)?;
        let floor = Rational::new(MINIMUM_DECIBELS, 1)?;
        let ceiling = Rational::new(MAXIMUM_DECIBELS, 1)?;
        Fader::at(held.clamp(floor, ceiling))
    }

    /// Drive this track's fader from a curve, or stop driving it.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::LevelOnPicture`] for a picture track, whose level is its
    /// opacity, and [`ModelStatus::WrongTimebase`] for a curve counted another
    /// way.
    pub(crate) fn set_level(&mut self, level: Option<Curve>) -> Result<Option<Curve>> {
        if let Some(curve) = &level {
            if self.kind != TrackKind::Audio {
                return Err(ModelStatus::LevelOnPicture);
            }
            if curve.timebase() != self.timebase {
                return Err(ModelStatus::WrongTimebase);
            }
        }
        Ok(core::mem::replace(&mut self.level, level))
    }

    /// One of this track's automation lanes.
    #[must_use]
    pub const fn curve(&self, lane: Automation) -> Option<&Curve> {
        match lane {
            Automation::Opacity => self.opacity.as_ref(),
            Automation::Level => self.level.as_ref(),
        }
    }

    /// Change one keyframe on one lane, giving back the change that undoes it.
    ///
    /// Adding to a lane with no automation starts one, and removing the last
    /// keyframe turns it off again. Those two are deliberately each other's
    /// inverse: an editor that adds a keyframe to a parameter nobody has
    /// animated expects the parameter to become animated, and undoing that
    /// expects it to stop — not to be left with a flat curve nobody asked for.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::OpacityOnSound`] or [`ModelStatus::LevelOnPicture`] for
    /// a lane this kind of track does not have,
    /// [`ModelStatus::NoAutomation`] for an operation on a lane that has none
    /// to change, and whatever the curve refuses.
    pub(crate) fn edit_keyframe(
        &mut self,
        lane: Automation,
        operation: KeyframeEdit,
    ) -> Result<KeyframeEdit> {
        self.check_lane(lane)?;
        match operation {
            KeyframeEdit::Add(keyframe) => {
                self.add_keyframe(lane, keyframe)?;
                Ok(KeyframeEdit::Remove(keyframe.at()))
            }
            KeyframeEdit::Remove(at) => self.remove_keyframe(lane, at),
            KeyframeEdit::Move { from, to } => {
                self.curve_mut(lane)?.move_keyframe(from, to)?;
                Ok(KeyframeEdit::Move { from: to, to: from })
            }
            KeyframeEdit::Set {
                at,
                value,
                interpolation,
            } => {
                let (value, interpolation) = self.curve_mut(lane)?.set(at, value, interpolation)?;
                Ok(KeyframeEdit::Set {
                    at,
                    value,
                    interpolation,
                })
            }
        }
    }

    /// Whether this track has the lane at all.
    fn check_lane(&self, lane: Automation) -> Result<()> {
        match (lane, self.kind) {
            (Automation::Opacity, TrackKind::Video) | (Automation::Level, TrackKind::Audio) => {
                Ok(())
            }
            (Automation::Opacity, TrackKind::Audio) => Err(ModelStatus::OpacityOnSound),
            (Automation::Level, TrackKind::Video) => Err(ModelStatus::LevelOnPicture),
        }
    }

    /// The curve on a lane, or a refusal if there is none to change.
    fn curve_mut(&mut self, lane: Automation) -> Result<&mut Curve> {
        let held = match lane {
            Automation::Opacity => self.opacity.as_mut(),
            Automation::Level => self.level.as_mut(),
        };
        held.ok_or(ModelStatus::NoAutomation)
    }

    /// Put a keyframe in, starting the lane if it has nothing on it.
    fn add_keyframe(&mut self, lane: Automation, keyframe: Keyframe) -> Result<()> {
        if self.curve(lane).is_none() {
            if keyframe.at().timebase() != self.timebase {
                return Err(ModelStatus::WrongTimebase);
            }
            let started = Curve::new({
                let mut held = alloc::vec::Vec::new();
                held.try_reserve(1).map_err(|_| ModelStatus::OutOfMemory)?;
                held.push(keyframe);
                held
            })?;
            match lane {
                Automation::Opacity => self.opacity = Some(started),
                Automation::Level => self.level = Some(started),
            }
            return Ok(());
        }
        self.curve_mut(lane)?.insert(keyframe)
    }

    /// Take a keyframe out, turning the lane off if it was the last.
    fn remove_keyframe(&mut self, lane: Automation, at: Instant) -> Result<KeyframeEdit> {
        let curve = self.curve_mut(lane)?;
        if curve.keyframes().len() == 1 {
            let only = curve.keyframes()[0];
            if only.at().ticks() != at.ticks() {
                return Err(ModelStatus::NoSuchKeyframe);
            }
            match lane {
                Automation::Opacity => self.opacity = None,
                Automation::Level => self.level = None,
            }
            return Ok(KeyframeEdit::Add(only));
        }
        Ok(KeyframeEdit::Add(curve.remove(at)?))
    }

    /// What this track carries.
    #[must_use]
    pub const fn kind(&self) -> TrackKind {
        self.kind
    }

    /// The rate this track is counted in.
    #[must_use]
    pub const fn timebase(&self) -> Timebase {
        self.timebase
    }

    /// How many items the track holds.
    #[must_use]
    pub fn len(&self) -> usize {
        self.items.len()
    }

    /// Whether the track holds nothing.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.items.is_empty()
    }

    /// The items, in order.
    #[must_use]
    pub fn items(&self) -> &[Item] {
        &self.items
    }

    /// One item.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::UnknownItem`] if the index names nothing.
    pub fn item(&self, index: usize) -> Result<&Item> {
        self.items.get(index).ok_or(ModelStatus::UnknownItem)
    }

    /// How long the whole track is.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::Time`] wrapping an overflow, which needs a track whose
    /// items sum past the representable range.
    pub fn duration(&self) -> Result<Duration> {
        let mut total = Duration::zero(self.timebase);
        for item in &self.items {
            total = total.checked_add(item.duration())?;
        }
        Ok(total)
    }

    /// Where an item begins on the track.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::UnknownItem`] if the index names nothing. An index equal
    /// to the item count is accepted and names the end of the track, which is
    /// where an append happens.
    pub fn item_start(&self, index: usize) -> Result<Instant> {
        if index > self.items.len() {
            return Err(ModelStatus::UnknownItem);
        }
        let mut start = Instant::origin(self.timebase);
        for item in &self.items[..index] {
            start = start.advance(item.duration())?;
        }
        Ok(start)
    }

    /// The range an item occupies on the track.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::UnknownItem`] if the index names nothing.
    pub fn item_range(&self, index: usize) -> Result<TimeRange> {
        let item = self.item(index)?;
        Ok(TimeRange::new(self.item_start(index)?, item.duration())?)
    }

    /// The item covering an instant, and how far into it that instant falls.
    ///
    /// Returns `None` for an instant at or past the end of the track, which is
    /// a real answer rather than a failure: the track simply does not reach.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::Time`] wrapping a timebase mismatch.
    pub fn item_at(&self, instant: Instant) -> Result<Option<(usize, i64)>> {
        if instant.timebase() != self.timebase {
            return Err(media_editor_core::CoreStatus::TimebaseMismatch.into());
        }
        if instant.ticks() < 0 {
            return Ok(None);
        }
        let mut start = Instant::origin(self.timebase);
        for (index, item) in self.items.iter().enumerate() {
            let end = start.advance(item.duration())?;
            if instant.ticks() < end.ticks() {
                return Ok(Some((index, instant.ticks() - start.ticks())));
            }
            start = end;
        }
        Ok(None)
    }

    /// Insert an item, moving everything after it later.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::UnknownItem`] for an index past the end,
    /// [`ModelStatus::EmptyItem`] for a zero-length item,
    /// [`ModelStatus::CapacityExhausted`], or [`ModelStatus::OutOfMemory`].
    pub fn insert(&mut self, index: usize, item: Item) -> Result<()> {
        if item.timebase() != self.timebase {
            return Err(media_editor_core::CoreStatus::TimebaseMismatch.into());
        }
        if self.transition_from(index) {
            return Err(ModelStatus::TransitionInTheWay);
        }
        if item.duration().is_zero() {
            return Err(ModelStatus::EmptyItem);
        }
        insert_bounded(&mut self.items, index, item, MAX_ITEMS_PER_TRACK)
    }

    /// Remove an item, moving everything after it earlier.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::UnknownItem`] if the index names nothing.
    pub fn remove(&mut self, index: usize) -> Result<Item> {
        if index >= self.items.len() {
            return Err(ModelStatus::UnknownItem);
        }
        if self.transition_from(index) {
            return Err(ModelStatus::TransitionInTheWay);
        }
        Ok(self.items.remove(index))
    }

    /// Replace an item in place.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::UnknownItem`] if the index names nothing.
    pub fn replace(&mut self, index: usize, item: Item) -> Result<Item> {
        if item.timebase() != self.timebase {
            return Err(media_editor_core::CoreStatus::TimebaseMismatch.into());
        }
        if item.duration().is_zero() {
            return Err(ModelStatus::EmptyItem);
        }
        let slot = self.items.get_mut(index).ok_or(ModelStatus::UnknownItem)?;
        Ok(core::mem::replace(slot, item))
    }

    /// Cut an item in two at an offset from its start.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::UnknownItem`], [`ModelStatus::SplitOutsideItem`],
    /// [`ModelStatus::CapacityExhausted`], or [`ModelStatus::OutOfMemory`].
    pub fn split(&mut self, index: usize, offset: i64) -> Result<()> {
        if self.transition_from(index + 1) {
            return Err(ModelStatus::TransitionInTheWay);
        }
        let (head, tail) = self.item(index)?.split(offset)?;
        // Reserve before either mutation, so a refusal leaves the track
        // exactly as it was (R-1.4).
        if self.items.len() >= MAX_ITEMS_PER_TRACK {
            return Err(ModelStatus::CapacityExhausted);
        }
        self.items
            .try_reserve(1)
            .map_err(|_| ModelStatus::OutOfMemory)?;
        self.replace(index, head)?;
        self.items.insert(index + 1, tail);
        Ok(())
    }

    /// Roll a cut by taking duration from one side and giving it to the other.
    ///
    /// `boundary` lies between `boundary - 1` and `boundary`. A positive `by`
    /// lengthens the outgoing item and advances the incoming source start while
    /// keeping programme duration fixed. Rolling by `-by` is the inverse.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::UnknownItem`] if the cut is not between two items,
    /// [`ModelStatus::EmptyItem`] if either side would be consumed entirely —
    /// a roll that eats a clip is a delete, and saying so is better than
    /// performing one — [`ModelStatus::SourceBeforeStart`] if the incoming
    /// side would have to start before its media does, and
    /// [`ModelStatus::TransitionTooLong`], [`ModelStatus::NotAClip`] or
    /// [`ModelStatus::SourceBeforeStart`] if a dissolve at or beside the cut
    /// would no longer fit what is left.
    pub fn roll(&mut self, boundary: usize, by: i64) -> Result<()> {
        // Only the lower end is checked here. A boundary past the last item
        // is refused by `self.item` a line later, and a control proved that:
        // adding the upper check as well was two mechanisms enforcing one
        // rule, and the rule was resting on whichever ran first. This one has
        // to stay, though — it is not a duplicate of anything, it is what
        // keeps `boundary - 1` from going round the houses.
        if boundary == 0 {
            return Err(ModelStatus::UnknownItem);
        }
        let outgoing = self.lengthened(boundary - 1, by)?;
        let incoming = self.shortened_from_the_front(boundary, by)?;
        self.commit(&[(boundary - 1, outgoing), (boundary, incoming)])
    }

    /// Move an item along its track, its neighbours absorbing the difference.
    ///
    /// The slide. The item itself does not change at all — same source, same
    /// length, same everything — it simply happens later or earlier, and the
    /// items either side give and take to make room. A positive `by` moves it
    /// later.
    ///
    /// So it needs a neighbour on both sides. An item at either end of a track
    /// has nothing to take the difference, and inventing a gap to absorb it
    /// would be a different edit performed silently.
    ///
    /// Its own inverse, like [`Track::roll`], and for the same reason.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::UnknownItem`] if the item has no neighbour on one side,
    /// [`ModelStatus::EmptyItem`] if a neighbour would be consumed entirely,
    /// [`ModelStatus::SourceBeforeStart`] if the following item would have to
    /// start before its media does, and whatever a dissolve beside it refuses.
    pub fn slide(&mut self, index: usize, by: i64) -> Result<()> {
        // As in [`Track::roll`]: the item after is checked by `self.item`, and
        // the item before is checked here because there is a subtraction.
        if index == 0 {
            return Err(ModelStatus::UnknownItem);
        }
        let before = self.lengthened(index - 1, by)?;
        let after = self.shortened_from_the_front(index + 1, by)?;
        self.commit(&[(index - 1, before), (index + 1, after)])
    }

    /// An item `by` ticks longer, keeping where it starts in its source.
    fn lengthened(&self, index: usize, by: i64) -> Result<Item> {
        let held = self.item(index)?;
        let ticks = held
            .duration()
            .ticks()
            .checked_add(by)
            .ok_or(ModelStatus::Time(media_editor_core::CoreStatus::Overflow))?;
        held.with_duration(Duration::new(ticks, self.timebase)?)
    }

    /// An item `by` ticks shorter, starting `by` ticks further into its media.
    ///
    /// Which is the half of a trim that is easy to leave out. Shortening an
    /// item from the front without moving its in point would keep the same
    /// opening frame and throw away the end, and that is a different edit —
    /// the one [`Track::split`] and [`Item::with_duration`] already do.
    fn shortened_from_the_front(&self, index: usize, by: i64) -> Result<Item> {
        let held = self.item(index)?;
        let ticks = held
            .duration()
            .ticks()
            .checked_sub(by)
            .ok_or(ModelStatus::Time(media_editor_core::CoreStatus::Overflow))?;
        let shorter = held.with_duration(Duration::new(ticks, self.timebase)?)?;
        Ok(match shorter {
            Item::Gap(duration) => Item::Gap(duration),
            Item::Clip(clip) => {
                let source = clip
                    .source_start()
                    .checked_add(by)
                    .ok_or(ModelStatus::Time(media_editor_core::CoreStatus::Overflow))?;
                Item::Clip(clip.with_source(source)?)
            }
        })
    }

    /// Put replacements in place, or leave the track exactly as it was.
    ///
    /// Every check happens before the first write. A trim that refused halfway
    /// would leave a track holding one side of a cut somebody did not make —
    /// which is the failure R-1.4 exists to forbid, and the one a two-item
    /// edit is most likely to produce.
    ///
    /// The check is asked of the *proposed* items rather than of a copy of the
    /// track, because a copy of a track is up to sixty-five thousand items and
    /// this runs on every frame of a drag.
    fn commit(&mut self, replacements: &[(usize, Item)]) -> Result<()> {
        for transition in &self.transitions {
            // Only a dissolve touching something that changed can have stopped
            // fitting. Checking every one would be correct and would make a
            // trim's cost the number of dissolves on the track.
            if replacements.iter().any(|(index, _)| {
                *index == transition.boundary || *index + 1 == transition.boundary
            }) {
                self.transition_fits(transition, replacements)?;
            }
        }
        for (index, item) in replacements {
            self.items[*index] = item.clone();
        }
        Ok(())
    }

    /// Join an item with the one after it.
    ///
    /// # Errors
    ///
    /// [`ModelStatus::UnknownItem`] or [`ModelStatus::ItemsNotContiguous`].
    pub fn join(&mut self, index: usize) -> Result<()> {
        if self.transition_from(index + 1) {
            return Err(ModelStatus::TransitionInTheWay);
        }
        let first = self.item(index)?.clone();
        let second = self.item(index + 1)?.clone();
        let joined = first.join(&second)?;
        self.replace(index, joined)?;
        self.items.remove(index + 1);
        Ok(())
    }
}
