# SPDX-License-Identifier: GPL-3.0-only
[workspace]
resolver = "3"
exclude = [
    "image",
]
members = [
    "crates/sapstudio-core",
    "crates/sapstudio-model",
    "crates/sapstudio-abi",
    "crates/sapstudio-media",
    "crates/sapstudio-audio",
    "crates/sapstudio-io",
    "crates/sapstudio-render",
    "crates/sapstudio-rt",
    "crates/sapstudio-app",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
rust-version = "1.85"
license = "GPL-3.0-only"
repository = "https://github.com/saudaljuaid/Phipia"

[profile.release]
panic = "abort"
opt-level = 2
lto = true
codegen-units = 1
overflow-checks = true
debug = true

[profile.dev]
panic = "abort"
overflow-checks = true
